# WARNING: This file is autogenerated by @atomic-ehr/codegen.
# GitHub: https://github.com/atomic-ehr/codegen
# Any manual changes made to this file may be overwritten.

from fhir_types.hl7_fhir_r4_core.profiles.extension_birth_place import BirthPlaceExtension
from fhir_types.hl7_fhir_r4_core.profiles.extension_birth_time import BirthTimeExtension
from fhir_types.hl7_fhir_r4_core.profiles.extension_nationality import (\
    NationalityExtension, NationalityCodeExtension, NationalityPeriodExtension
)
from fhir_types.hl7_fhir_r4_core.profiles.extension_own_prefix import OwnPrefixExtension
