// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-examples/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Period } from "../hl7-fhir-r4-examples/Period";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-examples/RelatedArtifact";
import type { UsageContext } from "../hl7-fhir-r4-examples/UsageContext";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-examples/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Period } from "../hl7-fhir-r4-examples/Period";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-examples/RelatedArtifact";
export type { UsageContext } from "../hl7-fhir-r4-examples/UsageContext";

export interface EffectEvidenceSynthesisCertainty extends BackboneElement {
    certaintySubcomponent?: EffectEvidenceSynthesisCertaintyCertaintySubcomponent[];
    note?: Annotation[];
    rating?: CodeableConcept[];
}

export interface EffectEvidenceSynthesisCertaintyCertaintySubcomponent extends BackboneElement {
    note?: Annotation[];
    rating?: CodeableConcept[];
    type?: CodeableConcept;
}

export interface EffectEvidenceSynthesisEffectEstimate extends BackboneElement {
    description?: string;
    precisionEstimate?: EffectEvidenceSynthesisEffectEstimatePrecisionEstimate[];
    type?: CodeableConcept;
    unitOfMeasure?: CodeableConcept;
    value?: number;
    variantState?: CodeableConcept;
}

export interface EffectEvidenceSynthesisEffectEstimatePrecisionEstimate extends BackboneElement {
    from?: number;
    level?: number;
    to?: number;
    type?: CodeableConcept;
}

export interface EffectEvidenceSynthesisResultsByExposure extends BackboneElement {
    description?: string;
    exposureState?: ("exposure" | "exposure-alternative");
    riskEvidenceSynthesis: Reference<"RiskEvidenceSynthesis">;
    variantState?: CodeableConcept;
}

export interface EffectEvidenceSynthesisSampleSize extends BackboneElement {
    description?: string;
    numberOfParticipants?: number;
    numberOfStudies?: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/EffectEvidenceSynthesis
export interface EffectEvidenceSynthesis extends DomainResource {
    resourceType: "EffectEvidenceSynthesis";

    approvalDate?: string;
    _approvalDate?: Element;
    author?: ContactDetail[];
    certainty?: EffectEvidenceSynthesisCertainty[];
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    editor?: ContactDetail[];
    effectEstimate?: EffectEvidenceSynthesisEffectEstimate[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    exposure: Reference<"EvidenceVariable">;
    exposureAlternative: Reference<"EvidenceVariable">;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    outcome: Reference<"EvidenceVariable">;
    population: Reference<"EvidenceVariable">;
    publisher?: string;
    _publisher?: Element;
    relatedArtifact?: RelatedArtifact[];
    resultsByExposure?: EffectEvidenceSynthesisResultsByExposure[];
    reviewer?: ContactDetail[];
    sampleSize?: EffectEvidenceSynthesisSampleSize;
    status: ("draft" | "active" | "retired" | "unknown");
    _status?: Element;
    studyType?: CodeableConcept;
    synthesisType?: CodeableConcept;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    url?: string;
    _url?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
}
export const isEffectEvidenceSynthesis = (resource: unknown): resource is EffectEvidenceSynthesis => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "EffectEvidenceSynthesis";
}
