// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from "../hl7-fhir-r4-examples/Age";
import type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Period } from "../hl7-fhir-r4-examples/Period";
import type { Range } from "../hl7-fhir-r4-examples/Range";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Age } from "../hl7-fhir-r4-examples/Age";
export type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Period } from "../hl7-fhir-r4-examples/Period";
export type { Range } from "../hl7-fhir-r4-examples/Range";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface FamilyMemberHistoryCondition extends BackboneElement {
    code: CodeableConcept;
    contributedToDeath?: boolean;
    note?: Annotation[];
    onsetAge?: Age;
    onsetPeriod?: Period;
    onsetRange?: Range;
    onsetString?: string;
    outcome?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/FamilyMemberHistory
export interface FamilyMemberHistory extends DomainResource {
    resourceType: "FamilyMemberHistory";

    ageAge?: Age;
    ageRange?: Range;
    ageString?: string;
    _ageString?: Element;
    bornDate?: string;
    _bornDate?: Element;
    bornPeriod?: Period;
    bornString?: string;
    _bornString?: Element;
    condition?: FamilyMemberHistoryCondition[];
    dataAbsentReason?: CodeableConcept;
    date?: string;
    _date?: Element;
    deceasedAge?: Age;
    deceasedBoolean?: boolean;
    _deceasedBoolean?: Element;
    deceasedDate?: string;
    _deceasedDate?: Element;
    deceasedRange?: Range;
    deceasedString?: string;
    _deceasedString?: Element;
    estimatedAge?: boolean;
    _estimatedAge?: Element;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    name?: string;
    _name?: Element;
    note?: Annotation[];
    patient: Reference<"Patient">;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"AllergyIntolerance" | "Condition" | "DiagnosticReport" | "DocumentReference" | "Observation" | "QuestionnaireResponse">[];
    relationship: CodeableConcept;
    sex?: CodeableConcept;
    status: ("partial" | "completed" | "entered-in-error" | "health-unknown");
    _status?: Element;
}
export const isFamilyMemberHistory = (resource: unknown): resource is FamilyMemberHistory => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "FamilyMemberHistory";
}
