// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Money } from "../hl7-fhir-r4-examples/Money";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Money } from "../hl7-fhir-r4-examples/Money";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface InvoiceLineItem extends BackboneElement {
    chargeItemCodeableConcept?: CodeableConcept;
    chargeItemReference?: Reference<"ChargeItem">;
    priceComponent?: InvoiceLineItemPriceComponent[];
    sequence?: number;
}

export interface InvoiceLineItemPriceComponent extends BackboneElement {
    amount?: Money;
    code?: CodeableConcept;
    factor?: number;
    type: ("base" | "surcharge" | "deduction" | "discount" | "tax" | "informational");
}

export interface InvoiceParticipant extends BackboneElement {
    actor: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    role?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Invoice
export interface Invoice extends DomainResource {
    resourceType: "Invoice";

    account?: Reference<"Account">;
    cancelledReason?: string;
    _cancelledReason?: Element;
    date?: string;
    _date?: Element;
    identifier?: Identifier[];
    issuer?: Reference<"Organization">;
    lineItem?: InvoiceLineItem[];
    note?: Annotation[];
    participant?: InvoiceParticipant[];
    paymentTerms?: string;
    _paymentTerms?: Element;
    recipient?: Reference<"Organization" | "Patient" | "RelatedPerson">;
    status: ("draft" | "issued" | "balanced" | "cancelled" | "entered-in-error");
    _status?: Element;
    subject?: Reference<"Group" | "Patient">;
    totalGross?: Money;
    totalNet?: Money;
    totalPriceComponent?: InvoiceLineItemPriceComponent[];
    type?: CodeableConcept;
}
export const isInvoice = (resource: unknown): resource is Invoice => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Invoice";
}
