// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../hl7-fhir-r4-examples/Address";
import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { Coding } from "../hl7-fhir-r4-examples/Coding";
import type { ContactPoint } from "../hl7-fhir-r4-examples/ContactPoint";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Address } from "../hl7-fhir-r4-examples/Address";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Coding } from "../hl7-fhir-r4-examples/Coding";
export type { ContactPoint } from "../hl7-fhir-r4-examples/ContactPoint";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface LocationHoursOfOperation extends BackboneElement {
    allDay?: boolean;
    closingTime?: string;
    daysOfWeek?: ("mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun")[];
    openingTime?: string;
}

export interface LocationPosition extends BackboneElement {
    altitude?: number;
    latitude: number;
    longitude: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Location
export interface Location extends DomainResource {
    resourceType: "Location";

    address?: Address;
    alias?: string[];
    _alias?: Element;
    availabilityExceptions?: string;
    _availabilityExceptions?: Element;
    description?: string;
    _description?: Element;
    endpoint?: Reference<"Endpoint">[];
    hoursOfOperation?: LocationHoursOfOperation[];
    identifier?: Identifier[];
    managingOrganization?: Reference<"Organization">;
    mode?: ("instance" | "kind");
    _mode?: Element;
    name?: string;
    _name?: Element;
    operationalStatus?: Coding;
    partOf?: Reference<"Location">;
    physicalType?: CodeableConcept;
    position?: LocationPosition;
    status?: ("active" | "suspended" | "inactive");
    _status?: Element;
    telecom?: ContactPoint[];
    type?: CodeableConcept[];
}
export const isLocation = (resource: unknown): resource is Location => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Location";
}
