// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { Period } from "../hl7-fhir-r4-examples/Period";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Period } from "../hl7-fhir-r4-examples/Period";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MarketingStatus
export interface MarketingStatus extends BackboneElement {
    country: CodeableConcept;
    dateRange: Period;
    jurisdiction?: CodeableConcept;
    restoreDate?: string;
    _restoreDate?: Element;
    status: CodeableConcept;
}
