// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Period } from "../hl7-fhir-r4-examples/Period";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Period } from "../hl7-fhir-r4-examples/Period";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface MedicinalProductAuthorizationJurisdictionalAuthorization extends BackboneElement {
    country?: CodeableConcept;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    legalStatusOfSupply?: CodeableConcept;
    validityPeriod?: Period;
}

export interface MedicinalProductAuthorizationProcedure extends BackboneElement {
    application?: MedicinalProductAuthorizationProcedure[];
    dateDateTime?: string;
    datePeriod?: Period;
    identifier?: Identifier;
    type: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MedicinalProductAuthorization
export interface MedicinalProductAuthorization extends DomainResource {
    resourceType: "MedicinalProductAuthorization";

    country?: CodeableConcept[];
    dataExclusivityPeriod?: Period;
    dateOfFirstAuthorization?: string;
    _dateOfFirstAuthorization?: Element;
    holder?: Reference<"Organization">;
    identifier?: Identifier[];
    internationalBirthDate?: string;
    _internationalBirthDate?: Element;
    jurisdiction?: CodeableConcept[];
    jurisdictionalAuthorization?: MedicinalProductAuthorizationJurisdictionalAuthorization[];
    legalBasis?: CodeableConcept;
    procedure?: MedicinalProductAuthorizationProcedure;
    regulator?: Reference<"Organization">;
    restoreDate?: string;
    _restoreDate?: Element;
    status?: CodeableConcept;
    statusDate?: string;
    _statusDate?: Element;
    subject?: Reference<"MedicinalProduct" | "MedicinalProductPackaged">;
    validityPeriod?: Period;
}
export const isMedicinalProductAuthorization = (resource: unknown): resource is MedicinalProductAuthorization => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MedicinalProductAuthorization";
}
