// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { ProdCharacteristic } from "../hl7-fhir-r4-examples/ProdCharacteristic";
import type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { ProdCharacteristic } from "../hl7-fhir-r4-examples/ProdCharacteristic";
export type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MedicinalProductManufactured
export interface MedicinalProductManufactured extends DomainResource {
    resourceType: "MedicinalProductManufactured";

    ingredient?: Reference<"MedicinalProductIngredient">[];
    manufacturedDoseForm: CodeableConcept;
    manufacturer?: Reference<"Organization">[];
    otherCharacteristics?: CodeableConcept[];
    physicalCharacteristics?: ProdCharacteristic;
    quantity: Quantity;
    unitOfPresentation?: CodeableConcept;
}
export const isMedicinalProductManufactured = (resource: unknown): resource is MedicinalProductManufactured => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MedicinalProductManufactured";
}
