// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Dosage } from "../hl7-fhir-r4-examples/Dosage";
import type { Duration } from "../hl7-fhir-r4-examples/Duration";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Period } from "../hl7-fhir-r4-examples/Period";
import type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Annotation } from "../hl7-fhir-r4-examples/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Dosage } from "../hl7-fhir-r4-examples/Dosage";
export type { Duration } from "../hl7-fhir-r4-examples/Duration";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Period } from "../hl7-fhir-r4-examples/Period";
export type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface MedicationRequestDispenseRequest extends BackboneElement {
    dispenseInterval?: Duration;
    expectedSupplyDuration?: Duration;
    initialFill?: MedicationRequestDispenseRequestInitialFill;
    numberOfRepeatsAllowed?: number;
    performer?: Reference<"Organization">;
    quantity?: Quantity;
    validityPeriod?: Period;
}

export interface MedicationRequestDispenseRequestInitialFill extends BackboneElement {
    duration?: Duration;
    quantity?: Quantity;
}

export interface MedicationRequestSubstitution extends BackboneElement {
    allowedBoolean?: boolean;
    allowedCodeableConcept?: CodeableConcept;
    reason?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MedicationRequest
export interface MedicationRequest extends DomainResource {
    resourceType: "MedicationRequest";

    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<"CarePlan" | "ImmunizationRecommendation" | "MedicationRequest" | "ServiceRequest">[];
    category?: CodeableConcept[];
    courseOfTherapyType?: CodeableConcept;
    detectedIssue?: Reference<"DetectedIssue">[];
    dispenseRequest?: MedicationRequestDispenseRequest;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    dosageInstruction?: Dosage[];
    encounter?: Reference<"Encounter">;
    eventHistory?: Reference<"Provenance">[];
    groupIdentifier?: Identifier;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<"ClaimResponse" | "Coverage">[];
    intent: ("proposal" | "plan" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    _intent?: Element;
    medicationCodeableConcept?: CodeableConcept;
    medicationReference?: Reference<"Medication">;
    note?: Annotation[];
    performer?: Reference<"CareTeam" | "Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    performerType?: CodeableConcept;
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    priorPrescription?: Reference<"MedicationRequest">;
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"Condition" | "Observation">[];
    recorder?: Reference<"Practitioner" | "PractitionerRole">;
    reportedBoolean?: boolean;
    _reportedBoolean?: Element;
    reportedReference?: Reference<"Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    requester?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    status: ("active" | "on-hold" | "cancelled" | "completed" | "entered-in-error" | "stopped" | "draft" | "unknown");
    _status?: Element;
    statusReason?: CodeableConcept;
    subject: Reference<"Group" | "Patient">;
    substitution?: MedicationRequestSubstitution;
    supportingInformation?: Reference<"Resource">[];
}
export const isMedicationRequest = (resource: unknown): resource is MedicationRequest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MedicationRequest";
}
