// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { Range } from "../hl7-fhir-r4-examples/Range";

export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Range } from "../hl7-fhir-r4-examples/Range";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Population
export interface Population extends BackboneElement {
    ageCodeableConcept?: CodeableConcept;
    ageRange?: Range;
    gender?: CodeableConcept;
    physiologicalCondition?: CodeableConcept;
    race?: CodeableConcept;
}
