// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Period } from "../hl7-fhir-r4-examples/Period";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";
import type { Signature } from "../hl7-fhir-r4-examples/Signature";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Period } from "../hl7-fhir-r4-examples/Period";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";
export type { Signature } from "../hl7-fhir-r4-examples/Signature";

export interface ProvenanceAgent extends BackboneElement {
    onBehalfOf?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    role?: CodeableConcept[];
    type?: CodeableConcept;
    who: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
}

export interface ProvenanceEntity extends BackboneElement {
    agent?: ProvenanceAgent[];
    role: ("derivation" | "revision" | "quotation" | "source" | "removal");
    what: Reference<"Resource">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Provenance
export interface Provenance extends DomainResource {
    resourceType: "Provenance";

    activity?: CodeableConcept;
    agent: ProvenanceAgent[];
    entity?: ProvenanceEntity[];
    location?: Reference<"Location">;
    occurredDateTime?: string;
    _occurredDateTime?: Element;
    occurredPeriod?: Period;
    policy?: string[];
    _policy?: Element;
    reason?: CodeableConcept[];
    recorded: string;
    _recorded?: Element;
    signature?: Signature[];
    target: Reference<"Resource">[];
}
export const isProvenance = (resource: unknown): resource is Provenance => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Provenance";
}
