// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { Element } from "../hl7-fhir-r4-examples/Element";
import type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
import type { Range } from "../hl7-fhir-r4-examples/Range";

export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Element } from "../hl7-fhir-r4-examples/Element";
export type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
export type { Range } from "../hl7-fhir-r4-examples/Range";

export interface SubstanceAmountReferenceRange extends Element {
    highLimit?: Quantity;
    lowLimit?: Quantity;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SubstanceAmount
export interface SubstanceAmount extends BackboneElement {
    amountQuantity?: Quantity;
    amountRange?: Range;
    amountString?: string;
    _amountString?: Element;
    amountText?: string;
    _amountText?: Element;
    amountType?: CodeableConcept;
    referenceRange?: Element;
}
