// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-examples/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
import type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
import type { Range } from "../hl7-fhir-r4-examples/Range";
import type { Reference } from "../hl7-fhir-r4-examples/Reference";

import type { Element } from "../hl7-fhir-r4-examples/Element";
export type { BackboneElement } from "../hl7-fhir-r4-examples/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-examples/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-examples/Identifier";
export type { Quantity } from "../hl7-fhir-r4-examples/Quantity";
export type { Range } from "../hl7-fhir-r4-examples/Range";
export type { Reference } from "../hl7-fhir-r4-examples/Reference";

export interface SubstanceReferenceInformationClassification extends BackboneElement {
    classification?: CodeableConcept;
    domain?: CodeableConcept;
    source?: Reference<"DocumentReference">[];
    subtype?: CodeableConcept[];
}

export interface SubstanceReferenceInformationGene extends BackboneElement {
    gene?: CodeableConcept;
    geneSequenceOrigin?: CodeableConcept;
    source?: Reference<"DocumentReference">[];
}

export interface SubstanceReferenceInformationGeneElement extends BackboneElement {
    element?: Identifier;
    source?: Reference<"DocumentReference">[];
    type?: CodeableConcept;
}

export interface SubstanceReferenceInformationTarget extends BackboneElement {
    amountQuantity?: Quantity;
    amountRange?: Range;
    amountString?: string;
    amountType?: CodeableConcept;
    interaction?: CodeableConcept;
    organism?: CodeableConcept;
    organismType?: CodeableConcept;
    source?: Reference<"DocumentReference">[];
    target?: Identifier;
    type?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SubstanceReferenceInformation
export interface SubstanceReferenceInformation extends DomainResource {
    resourceType: "SubstanceReferenceInformation";

    classification?: SubstanceReferenceInformationClassification[];
    comment?: string;
    _comment?: Element;
    gene?: SubstanceReferenceInformationGene[];
    geneElement?: SubstanceReferenceInformationGeneElement[];
    target?: SubstanceReferenceInformationTarget[];
}
export const isSubstanceReferenceInformation = (resource: unknown): resource is SubstanceReferenceInformation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SubstanceReferenceInformation";
}
