// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { AllergyIntolerance } from "../../hl7-fhir-r4-core/AllergyIntolerance";
import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

export interface USCoreAllergyIntolerance extends AllergyIntolerance {
    code: CodeableConcept;
}

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type USCoreAllergyIntoleranceProfileParams = {
    code: CodeableConcept;
    patient: Reference<"USCorePatientProfile">;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreAllergyIntoleranceProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance"

    private resource: AllergyIntolerance

    constructor (resource: AllergyIntolerance) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance")) profiles.push("http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance")
    }

    static from (resource: AllergyIntolerance) : USCoreAllergyIntoleranceProfile {
        return new USCoreAllergyIntoleranceProfile(resource)
    }

    static createResource (args: USCoreAllergyIntoleranceProfileParams) : AllergyIntolerance {
        const resource: AllergyIntolerance = {
            resourceType: "AllergyIntolerance",
            code: args.code,
            patient: args.patient,
            meta: { profile: ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance"] },
        } as unknown as AllergyIntolerance
        return resource
    }

    static create (args: USCoreAllergyIntoleranceProfileParams) : USCoreAllergyIntoleranceProfile {
        return USCoreAllergyIntoleranceProfile.from(USCoreAllergyIntoleranceProfile.createResource(args))
    }

    toResource () : AllergyIntolerance {
        return this.resource
    }

    getCode () : CodeableConcept | undefined {
        return this.resource.code as CodeableConcept | undefined
    }

    setCode (value: CodeableConcept) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getPatient () : Reference<"USCorePatientProfile"> | undefined {
        return this.resource.patient as Reference<"USCorePatientProfile"> | undefined
    }

    setPatient (value: Reference<"USCorePatientProfile">) : this {
        Object.assign(this.resource, { patient: value })
        return this
    }

    toProfile () : USCoreAllergyIntolerance {
        return this.resource as USCoreAllergyIntolerance
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateEnum(r["clinicalStatus"], ["active","inactive","resolved"], "clinicalStatus", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        { const e = validateEnum(r["verificationStatus"], ["unconfirmed","confirmed","refuted","entered-in-error"], "verificationStatus", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        { const e = validateRequired(r, "code", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        { const e = validateRequired(r, "patient", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        { const e = validateReference(r["patient"], ["USCorePatientProfile"], "patient", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        { const e = validateReference(r["recorder"], ["PractitionerRole","USCorePatientProfile","USCorePractitionerProfile","USCoreRelatedPersonProfile"], "recorder", "USCoreAllergyIntolerance"); if (e) errors.push(e) }
        return errors
    }

}

