// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

export type USCoreRaceExtension_Extension_OmbCategorySliceInput = Omit<Extension, "url">;
export type USCoreRaceExtension_Extension_DetailedSliceInput = Omit<Extension, "url">;
export type USCoreRaceExtension_Extension_TextSliceInput = Omit<Extension, "url">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-race (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreRaceExtensionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : USCoreRaceExtensionProfile {
        return new USCoreRaceExtensionProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            extension: [{"url":"text"}],
            url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        } as unknown as Extension
        return resource
    }

    static create () : USCoreRaceExtensionProfile {
        return USCoreRaceExtensionProfile.from(USCoreRaceExtensionProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setExtensionOmbCategory (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "ombCategory", ...value })
        return this
    }

    public setExtensionDetailed (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "detailed", ...value })
        return this
    }

    public setExtensionText (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "text", ...value })
        return this
    }

    public setSliceExtensionOmbCategory (input?: USCoreRaceExtension_Extension_OmbCategorySliceInput): this {
        const match = {"url":"ombCategory"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Extension
        const list = (this.resource.extension ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setSliceExtensionDetailed (input?: USCoreRaceExtension_Extension_DetailedSliceInput): this {
        const match = {"url":"detailed"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Extension
        const list = (this.resource.extension ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setSliceExtensionText (input?: USCoreRaceExtension_Extension_TextSliceInput): this {
        const match = {"url":"text"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Extension
        const list = (this.resource.extension ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getOmbCategory (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "ombCategory")
    }

    public getDetailed (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "detailed")
    }

    public getText (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "text")
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "USCoreRaceExtension"); if (e) errors.push(e) }
        errors.push(...validateSliceCardinality(r["extension"] as unknown[] | undefined, {"url":"ombCategory"}, "ombCategory", 0, 6, "USCoreRaceExtension.extension"))
        errors.push(...validateSliceCardinality(r["extension"] as unknown[] | undefined, {"url":"text"}, "text", 1, 1, "USCoreRaceExtension.extension"))
        { const e = validateRequired(r, "url", "USCoreRaceExtension"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race", "USCoreRaceExtension"); if (e) errors.push(e) }
        return errors
    }

}

