// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Period } from "../../hl7-fhir-r4-core/Period";
import type { Quantity } from "../../hl7-fhir-r4-core/Quantity";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

export interface USCoreSmokingStatusProfile extends Observation {
    category: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[];
    subject: Reference<"Patient">;
}

export type USCoreSmokingStatusProfile_Category_SocialHistorySliceInput = Omit<CodeableConcept, "coding">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type USCoreSmokingStatusProfileProfileParams = {
    status: ("final" | "entered-in-error");
    code: CodeableConcept<("11367-0" | "401201003" | "72166-2" | "782516008" | string)>;
    subject: Reference<"USCorePatientProfile">;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreSmokingStatusProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus"

    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus")) profiles.push("http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus")
    }

    static from (resource: Observation) : USCoreSmokingStatusProfileProfile {
        return new USCoreSmokingStatusProfileProfile(resource)
    }

    static createResource (args: USCoreSmokingStatusProfileProfileParams) : Observation {
        const resource: Observation = {
            resourceType: "Observation",
            category: [{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"social-history"}]}],
            status: args.status,
            code: args.code,
            subject: args.subject,
            meta: { profile: ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus"] },
        } as unknown as Observation
        return resource
    }

    static create (args: USCoreSmokingStatusProfileProfileParams) : USCoreSmokingStatusProfileProfile {
        return USCoreSmokingStatusProfileProfile.from(USCoreSmokingStatusProfileProfile.createResource(args))
    }

    toResource () : Observation {
        return this.resource
    }

    getStatus () : ("final" | "entered-in-error") | undefined {
        return this.resource.status as ("final" | "entered-in-error") | undefined
    }

    setStatus (value: ("final" | "entered-in-error")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getCode () : CodeableConcept<("11367-0" | "401201003" | "72166-2" | "782516008" | string)> | undefined {
        return this.resource.code as CodeableConcept<("11367-0" | "401201003" | "72166-2" | "782516008" | string)> | undefined
    }

    setCode (value: CodeableConcept<("11367-0" | "401201003" | "72166-2" | "782516008" | string)>) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getSubject () : Reference<"USCorePatientProfile"> | undefined {
        return this.resource.subject as Reference<"USCorePatientProfile"> | undefined
    }

    setSubject (value: Reference<"USCorePatientProfile">) : this {
        Object.assign(this.resource, { subject: value })
        return this
    }

    getCategory () : CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined {
        return this.resource.category as CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined
    }

    setCategory (value: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[]) : this {
        Object.assign(this.resource, { category: value })
        return this
    }

    getEffectiveDateTime () : string | undefined {
        return this.resource.effectiveDateTime as string | undefined
    }

    setEffectiveDateTime (value: string) : this {
        Object.assign(this.resource, { effectiveDateTime: value })
        return this
    }

    getEffectivePeriod () : Period | undefined {
        return this.resource.effectivePeriod as Period | undefined
    }

    setEffectivePeriod (value: Period) : this {
        Object.assign(this.resource, { effectivePeriod: value })
        return this
    }

    getValueQuantity () : Quantity | undefined {
        return this.resource.valueQuantity as Quantity | undefined
    }

    setValueQuantity (value: Quantity) : this {
        Object.assign(this.resource, { valueQuantity: value })
        return this
    }

    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value })
        return this
    }

    toProfile () : USCoreSmokingStatusProfile {
        return this.resource as USCoreSmokingStatusProfile
    }

    public setSocialHistory (input?: USCoreSmokingStatusProfile_Category_SocialHistorySliceInput): this {
        const match = {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"social-history"}]} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as CodeableConcept
        const list = (this.resource.category ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getSocialHistory (): USCoreSmokingStatusProfile_Category_SocialHistorySliceInput | undefined {
        const match = {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"social-history"}]} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["coding"]) as USCoreSmokingStatusProfile_Category_SocialHistorySliceInput
    }

    public getSocialHistoryRaw (): CodeableConcept | undefined {
        const match = {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"social-history"}]} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "status", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["final","entered-in-error"], "status", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "category", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        errors.push(...validateSliceCardinality(r["category"] as unknown[] | undefined, {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/observation-category","code":"social-history"}]}, "SocialHistory", 1, 1, "USCoreSmokingStatusProfile.category"))
        { const e = validateRequired(r, "code", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "subject", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["subject"], ["USCorePatientProfile"], "subject", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        if (!(r["effectiveDateTime"] !== undefined || r["effectivePeriod"] !== undefined)) {
            errors.push("effective: at least one of effectiveDateTime, effectivePeriod is required")
        }
        { const e = validateReference(r["performer"], ["PractitionerRole","USCoreCareTeam","USCoreOrganizationProfile","USCorePatientProfile","USCorePractitionerProfile","USCoreRelatedPersonProfile"], "performer", "USCoreSmokingStatusProfile"); if (e) errors.push(e) }
        return errors
    }

}

