// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Identifier } from "../../hl7-fhir-r4-core/Identifier";
import type { Organization } from "../../hl7-fhir-r4-core/Organization";

export interface USCoreOrganizationProfile extends Organization {
    active: boolean;
    name: string;
}

export type USCoreOrganizationProfile_Identifier_NPISliceInput = Omit<Identifier, "system">;
export type USCoreOrganizationProfile_Identifier_CLIASliceInput = Omit<Identifier, "system">;
export type USCoreOrganizationProfile_Identifier_NAICSliceInput = Omit<Identifier, "system">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type USCoreOrganizationProfileProfileParams = {
    active: boolean;
    name: string;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreOrganizationProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization"

    private resource: Organization

    constructor (resource: Organization) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization")) profiles.push("http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization")
    }

    static from (resource: Organization) : USCoreOrganizationProfileProfile {
        return new USCoreOrganizationProfileProfile(resource)
    }

    static createResource (args: USCoreOrganizationProfileProfileParams) : Organization {
        const resource: Organization = {
            resourceType: "Organization",
            active: args.active,
            name: args.name,
            meta: { profile: ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization"] },
        } as unknown as Organization
        return resource
    }

    static create (args: USCoreOrganizationProfileProfileParams) : USCoreOrganizationProfileProfile {
        return USCoreOrganizationProfileProfile.from(USCoreOrganizationProfileProfile.createResource(args))
    }

    toResource () : Organization {
        return this.resource
    }

    getActive () : boolean | undefined {
        return this.resource.active as boolean | undefined
    }

    setActive (value: boolean) : this {
        Object.assign(this.resource, { active: value })
        return this
    }

    getName () : string | undefined {
        return this.resource.name as string | undefined
    }

    setName (value: string) : this {
        Object.assign(this.resource, { name: value })
        return this
    }

    toProfile () : USCoreOrganizationProfile {
        return this.resource as USCoreOrganizationProfile
    }

    public setNPI (input?: USCoreOrganizationProfile_Identifier_NPISliceInput): this {
        const match = {"system":"http://hl7.org/fhir/sid/us-npi"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Identifier
        const list = (this.resource.identifier ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setCLIA (input?: USCoreOrganizationProfile_Identifier_CLIASliceInput): this {
        const match = {"system":"urn:oid:2.16.840.1.113883.4.7"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Identifier
        const list = (this.resource.identifier ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setNAIC (input?: USCoreOrganizationProfile_Identifier_NAICSliceInput): this {
        const match = {"system":"urn:oid:2.16.840.1.113883.6.300"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as Identifier
        const list = (this.resource.identifier ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getNPI (): USCoreOrganizationProfile_Identifier_NPISliceInput | undefined {
        const match = {"system":"http://hl7.org/fhir/sid/us-npi"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["system"]) as USCoreOrganizationProfile_Identifier_NPISliceInput
    }

    public getNPIRaw (): Identifier | undefined {
        const match = {"system":"http://hl7.org/fhir/sid/us-npi"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getCLIA (): USCoreOrganizationProfile_Identifier_CLIASliceInput | undefined {
        const match = {"system":"urn:oid:2.16.840.1.113883.4.7"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["system"]) as USCoreOrganizationProfile_Identifier_CLIASliceInput
    }

    public getCLIARaw (): Identifier | undefined {
        const match = {"system":"urn:oid:2.16.840.1.113883.4.7"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getNAIC (): USCoreOrganizationProfile_Identifier_NAICSliceInput | undefined {
        const match = {"system":"urn:oid:2.16.840.1.113883.6.300"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["system"]) as USCoreOrganizationProfile_Identifier_NAICSliceInput
    }

    public getNAICRaw (): Identifier | undefined {
        const match = {"system":"urn:oid:2.16.840.1.113883.6.300"} as Record<string, unknown>
        const list = this.resource.identifier
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "active", "USCoreOrganizationProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "name", "USCoreOrganizationProfile"); if (e) errors.push(e) }
        return errors
    }

}

