// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Period } from "../../hl7-fhir-r4-core/Period";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";
import type { ServiceRequest } from "../../hl7-fhir-r4-core/ServiceRequest";
import type { Timing } from "../../hl7-fhir-r4-core/Timing";

export interface USCoreServiceRequestProfile extends ServiceRequest {
    code: CodeableConcept;
}

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type USCoreServiceRequestProfileProfileParams = {
    status: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown");
    intent: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    code: CodeableConcept;
    subject: Reference<"Device" | "Group" | "USCoreLocationProfile" | "USCorePatientProfile">;
}

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-servicerequest (pkg: hl7.fhir.us.core#8.0.1)
export class USCoreServiceRequestProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-servicerequest"

    private resource: ServiceRequest

    constructor (resource: ServiceRequest) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/us/core/StructureDefinition/us-core-servicerequest")) profiles.push("http://hl7.org/fhir/us/core/StructureDefinition/us-core-servicerequest")
    }

    static from (resource: ServiceRequest) : USCoreServiceRequestProfileProfile {
        return new USCoreServiceRequestProfileProfile(resource)
    }

    static createResource (args: USCoreServiceRequestProfileProfileParams) : ServiceRequest {
        const resource: ServiceRequest = {
            resourceType: "ServiceRequest",
            status: args.status,
            intent: args.intent,
            code: args.code,
            subject: args.subject,
            meta: { profile: ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-servicerequest"] },
        } as unknown as ServiceRequest
        return resource
    }

    static create (args: USCoreServiceRequestProfileProfileParams) : USCoreServiceRequestProfileProfile {
        return USCoreServiceRequestProfileProfile.from(USCoreServiceRequestProfileProfile.createResource(args))
    }

    toResource () : ServiceRequest {
        return this.resource
    }

    getStatus () : ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown") | undefined
    }

    setStatus (value: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getIntent () : ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option") | undefined {
        return this.resource.intent as ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option") | undefined
    }

    setIntent (value: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option")) : this {
        Object.assign(this.resource, { intent: value })
        return this
    }

    getCode () : CodeableConcept | undefined {
        return this.resource.code as CodeableConcept | undefined
    }

    setCode (value: CodeableConcept) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getSubject () : Reference<"Device" | "Group" | "USCoreLocationProfile" | "USCorePatientProfile"> | undefined {
        return this.resource.subject as Reference<"Device" | "Group" | "USCoreLocationProfile" | "USCorePatientProfile"> | undefined
    }

    setSubject (value: Reference<"Device" | "Group" | "USCoreLocationProfile" | "USCorePatientProfile">) : this {
        Object.assign(this.resource, { subject: value })
        return this
    }

    getOccurrencePeriod () : Period | undefined {
        return this.resource.occurrencePeriod as Period | undefined
    }

    setOccurrencePeriod (value: Period) : this {
        Object.assign(this.resource, { occurrencePeriod: value })
        return this
    }

    getOccurrenceDateTime () : string | undefined {
        return this.resource.occurrenceDateTime as string | undefined
    }

    setOccurrenceDateTime (value: string) : this {
        Object.assign(this.resource, { occurrenceDateTime: value })
        return this
    }

    getOccurrenceTiming () : Timing | undefined {
        return this.resource.occurrenceTiming as Timing | undefined
    }

    setOccurrenceTiming (value: Timing) : this {
        Object.assign(this.resource, { occurrenceTiming: value })
        return this
    }

    toProfile () : USCoreServiceRequestProfile {
        return this.resource as USCoreServiceRequestProfile
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "status", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["draft","active","on-hold","revoked","completed","entered-in-error","unknown"], "status", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "intent", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateEnum(r["intent"], ["proposal","plan","directive","order","original-order","reflex-order","filler-order","instance-order","option"], "intent", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "code", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "subject", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["subject"], ["Device","Group","USCoreLocationProfile","USCorePatientProfile"], "subject", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["encounter"], ["USCoreEncounterProfile"], "encounter", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["requester"], ["Device","PractitionerRole","USCoreOrganizationProfile","USCorePatientProfile","USCorePractitionerProfile","USCoreRelatedPersonProfile"], "requester", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["reasonReference"], ["Condition","DiagnosticReport","DocumentReference","Observation"], "reasonReference", "USCoreServiceRequestProfile"); if (e) errors.push(e) }
        return errors
    }

}

