// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-treatment-intervention-preference
export interface USCoreTreatmentInterventionPreferenceProfile extends Observation {
    subject: Reference<"Patient">;
}

export type USCoreTreatmentInterventionPreferenceProfile_Category_Us_coreSliceInput = Omit<CodeableConcept, "coding">;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class USCoreTreatmentInterventionPreferenceProfileProfile {
    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
    }

    toResource () : Observation {
        return this.resource
    }

    toProfile () : USCoreTreatmentInterventionPreferenceProfile {
        return this.resource as USCoreTreatmentInterventionPreferenceProfile
    }

    public setUsCore (input?: USCoreTreatmentInterventionPreferenceProfile_Category_Us_coreSliceInput): this {
        const match = {"coding":[{"system":"http://hl7.org/fhir/us/core/CodeSystem/us-core-category","code":"treatment-intervention-preference"}]} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as CodeableConcept
        const list = (this.resource.category ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getUsCore (): USCoreTreatmentInterventionPreferenceProfile_Category_Us_coreSliceInput | undefined {
        const match = {"coding":[{"system":"http://hl7.org/fhir/us/core/CodeSystem/us-core-category","code":"treatment-intervention-preference"}]} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["coding"]) as USCoreTreatmentInterventionPreferenceProfile_Category_Us_coreSliceInput
    }

    public getUsCoreRaw (): CodeableConcept | undefined {
        const match = {"coding":[{"system":"http://hl7.org/fhir/us/core/CodeSystem/us-core-category","code":"treatment-intervention-preference"}]} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

