// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Location } from "../../hl7-fhir-r4-core/Location";

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-location
export class USCoreLocationProfileProfile {
    private resource: Location

    constructor (resource?: Location) {
        this.resource = resource ?? ({ resourceType: "Location" } as Location)
    }

    toResource () : Location {
        return this.resource
    }

}

