// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Device } from "../../hl7-fhir-r4-core/Device";

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-implantable-device
export class USCoreImplantableDeviceProfileProfile {
    private resource: Device

    constructor (resource?: Device) {
        this.resource = resource ?? ({ resourceType: "Device" } as Device)
    }

    toResource () : Device {
        return this.resource
    }

}

