// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Condition } from "../../hl7-fhir-r4-core/Condition";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

// CanonicalURL: http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns
export interface USCoreConditionProblemsHealthConcernsProfile extends Condition {
    category: CodeableConcept[];
    code: CodeableConcept;
}

export class USCoreConditionProblemsHealthConcernsProfileProfile {
    private resource: Condition

    constructor (resource: Condition) {
        this.resource = resource
    }

    toResource () : Condition {
        return this.resource
    }

    toProfile () : USCoreConditionProblemsHealthConcernsProfile {
        return this.resource as USCoreConditionProblemsHealthConcernsProfile
    }

    public setAssertedDate (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/condition-assertedDate", valueDateTime: value })
        return this
    }

    public resetAssertedDate (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/condition-assertedDate")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public getAssertedDate(raw: true): Extension | undefined
    public getAssertedDate(raw?: false): string | undefined
    public getAssertedDate (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/condition-assertedDate")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueDateTime
    }

}

