// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://terminology.hl7.org/StructureDefinition/ext-namingsystem-title (pkg: hl7.terminology.r5#5.3.0)
export class NamingSystemTitleProfile {
    static readonly canonicalUrl = "http://terminology.hl7.org/StructureDefinition/ext-namingsystem-title"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : NamingSystemTitleProfile {
        return new NamingSystemTitleProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://terminology.hl7.org/StructureDefinition/ext-namingsystem-title",
        } as unknown as Extension
        return resource
    }

    static create () : NamingSystemTitleProfile {
        return NamingSystemTitleProfile.from(NamingSystemTitleProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "NamingSystemTitle"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://terminology.hl7.org/StructureDefinition/ext-namingsystem-title", "NamingSystemTitle"); if (e) errors.push(e) }
        return errors
    }

}

