// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { ContactPoint } from "../../hl7-fhir-r4-core/ContactPoint";
import type { Endpoint } from "../../hl7-fhir-r4-core/Endpoint";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

export interface UserAccessEndpoint extends Endpoint {
    contact: ContactPoint[];
}

export type UserAccessEndpoint_Contact_Configuration_urlSliceInput = Omit<ContactPoint, "system">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type UserAccessEndpointProfileParams = {
    extension: Extension[];
    status: ("active" | "suspended" | "error" | "off" | "entered-in-error" | "test");
    address: string;
}

// CanonicalURL: http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint (pkg: hl7.fhir.uv.smart-app-launch#2.2.0)
export class UserAccessEndpointProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint"

    private resource: Endpoint

    constructor (resource: Endpoint) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint")) profiles.push("http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint")
    }

    static from (resource: Endpoint) : UserAccessEndpointProfile {
        return new UserAccessEndpointProfile(resource)
    }

    static createResource (args: UserAccessEndpointProfileParams) : Endpoint {
        const resource: Endpoint = {
            resourceType: "Endpoint",
            connectionType: {"system":"http://terminology.hl7.org/CodeSystem/endpoint-connection-type","code":"hl7-fhir-rest"},
            contact: [{"system":"url"}],
            payloadType: [{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/endpoint-payload-type","code":"none"}]}],
            extension: args.extension,
            status: args.status,
            address: args.address,
            meta: { profile: ["http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint"] },
        } as unknown as Endpoint
        return resource
    }

    static create (args: UserAccessEndpointProfileParams) : UserAccessEndpointProfile {
        return UserAccessEndpointProfile.from(UserAccessEndpointProfile.createResource(args))
    }

    toResource () : Endpoint {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getStatus () : ("active" | "suspended" | "error" | "off" | "entered-in-error" | "test") | undefined {
        return this.resource.status as ("active" | "suspended" | "error" | "off" | "entered-in-error" | "test") | undefined
    }

    setStatus (value: ("active" | "suspended" | "error" | "off" | "entered-in-error" | "test")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getAddress () : string | undefined {
        return this.resource.address as string | undefined
    }

    setAddress (value: string) : this {
        Object.assign(this.resource, { address: value })
        return this
    }

    getConnectionType () : Coding<("ihe-xcpd" | "ihe-xca" | "ihe-xdr" | "ihe-xds" | "ihe-iid" | "dicom-wado-rs" | "dicom-qido-rs" | "dicom-stow-rs" | "dicom-wado-uri" | "hl7-fhir-rest" | "hl7-fhir-msg" | "hl7v2-mllp" | "secure-email" | "direct-project" | string)> | undefined {
        return this.resource.connectionType as Coding<("ihe-xcpd" | "ihe-xca" | "ihe-xdr" | "ihe-xds" | "ihe-iid" | "dicom-wado-rs" | "dicom-qido-rs" | "dicom-stow-rs" | "dicom-wado-uri" | "hl7-fhir-rest" | "hl7-fhir-msg" | "hl7v2-mllp" | "secure-email" | "direct-project" | string)> | undefined
    }

    setConnectionType (value: Coding<("ihe-xcpd" | "ihe-xca" | "ihe-xdr" | "ihe-xds" | "ihe-iid" | "dicom-wado-rs" | "dicom-qido-rs" | "dicom-stow-rs" | "dicom-wado-uri" | "hl7-fhir-rest" | "hl7-fhir-msg" | "hl7v2-mllp" | "secure-email" | "direct-project" | string)>) : this {
        Object.assign(this.resource, { connectionType: value })
        return this
    }

    getContact () : ContactPoint[] | undefined {
        return this.resource.contact as ContactPoint[] | undefined
    }

    setContact (value: ContactPoint[]) : this {
        Object.assign(this.resource, { contact: value })
        return this
    }

    getPayloadType () : CodeableConcept[] | undefined {
        return this.resource.payloadType as CodeableConcept[] | undefined
    }

    setPayloadType (value: CodeableConcept[]) : this {
        Object.assign(this.resource, { payloadType: value })
        return this
    }

    toProfile () : UserAccessEndpoint {
        return this.resource as UserAccessEndpoint
    }

    public setFhirVersion (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/endpoint-fhir-version", valueCode: value } as Extension)
        return this
    }

    public setConfigurationUrl (input?: UserAccessEndpoint_Contact_Configuration_urlSliceInput): this {
        const match = {"system":"url"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as ContactPoint
        const list = (this.resource.contact ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getFhirVersion (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/endpoint-fhir-version")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getFhirVersionExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/endpoint-fhir-version")
        return ext
    }

    public getConfigurationUrl (): UserAccessEndpoint_Contact_Configuration_urlSliceInput | undefined {
        const match = {"system":"url"} as Record<string, unknown>
        const list = this.resource.contact
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["system"]) as UserAccessEndpoint_Contact_Configuration_urlSliceInput
    }

    public getConfigurationUrlRaw (): ContactPoint | undefined {
        const match = {"system":"url"} as Record<string, unknown>
        const list = this.resource.contact
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateRequired(r, "status", "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["active","suspended","error","off","entered-in-error","test"], "status", "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateRequired(r, "connectionType", "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "connectionType", {"system":"http://terminology.hl7.org/CodeSystem/endpoint-connection-type","code":"hl7-fhir-rest"}, "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateRequired(r, "contact", "UserAccessEndpoint"); if (e) errors.push(e) }
        errors.push(...validateSliceCardinality(r["contact"] as unknown[] | undefined, {"system":"url"}, "configuration-url", 1, 0, "UserAccessEndpoint.contact"))
        { const e = validateRequired(r, "payloadType", "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "payloadType", {"coding":[{"system":"http://terminology.hl7.org/CodeSystem/endpoint-payload-type","code":"none"}]}, "UserAccessEndpoint"); if (e) errors.push(e) }
        { const e = validateRequired(r, "address", "UserAccessEndpoint"); if (e) errors.push(e) }
        return errors
    }

}

