// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { ContactPoint } from "../../hl7-fhir-r4-core/ContactPoint";
import type { Endpoint } from "../../hl7-fhir-r4-core/Endpoint";

// CanonicalURL: http://hl7.org/fhir/smart-app-launch/StructureDefinition/user-access-endpoint
export type UserAccessEndpoint_Contact_Configuration_urlSliceInput = Omit<ContactPoint, "system"> & Required<Pick<ContactPoint, "value">>;

import { applySliceMatch, matchesSlice } from "../../profile-helpers";

export class UserAccessEndpointProfile {
    private resource: Endpoint

    constructor (resource?: Endpoint) {
        this.resource = resource ?? ({ resourceType: "Endpoint" } as Endpoint)
    }

    toResource () : Endpoint {
        return this.resource
    }

    public setFhirVersion (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/endpoint-fhir-version", valueCode: value })
        return this
    }

    public setConfigurationUrl (input: UserAccessEndpoint_Contact_Configuration_urlSliceInput): this {
        const match = {"system":"url"} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as ContactPoint
        const list = (this.resource.contact ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public resetFhirVersion (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/endpoint-fhir-version")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetConfigurationUrl (): this {
        const match = {"system":"url"} as Record<string, unknown>
        const list = this.resource.contact
        if (list) {
            const index = list.findIndex((item) => matchesSlice(item, match))
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

}

