// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Meta } from "../hl7-fhir-r4-core/Meta";

export type { Meta } from "../hl7-fhir-r4-core/Meta";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Resource
export interface Resource {
    resourceType: "CodeSystem" | "DomainResource" | "Resource" | "ValueSet";

    id?: string;
    implicitRules?: string;
    language?: string;
    meta?: Meta;
}
export const isResource = (resource: unknown): resource is Resource => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Resource";
}
