// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../../hl7-fhir-r4-core/Address";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type birthPlaceProfileParams = {
    valueAddress: Address;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthPlace (pkg: hl7.fhir.r4.core#4.0.1)
export class birthPlaceProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : birthPlaceProfile {
        return new birthPlaceProfile(resource)
    }

    static createResource (args: birthPlaceProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            valueAddress: args.valueAddress,
        } as unknown as Extension
        return resource
    }

    static create (args: birthPlaceProfileParams) : birthPlaceProfile {
        return birthPlaceProfile.from(birthPlaceProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueAddress () : Address | undefined {
        return this.resource.valueAddress as Address | undefined
    }

    setValueAddress (value: Address) : this {
        Object.assign(this.resource, { valueAddress: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "birthPlace"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthPlace", "birthPlace"); if (e) errors.push(e) }
        if (!(r["valueAddress"] !== undefined)) {
            errors.push("value: at least one of valueAddress is required")
        }
        return errors
    }

}

