// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference, validateChoiceRequired } from "../../profile-helpers";

export type birthTimeProfileParams = {
    valueDateTime: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-birthTime (pkg: hl7.fhir.r4.core#4.0.1)
export class birthTimeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-birthTime"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : birthTimeProfile {
        return new birthTimeProfile(resource)
    }

    static createResource (args: birthTimeProfileParams) : Extension {
        const resource = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
            valueDateTime: args.valueDateTime,
        } as unknown as Extension
        return resource
    }

    static create (args: birthTimeProfileParams) : birthTimeProfile {
        return birthTimeProfile.from(birthTimeProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    // Field accessors

    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    // Validation

    validate(): string[] {
        const profileName = "birthTime"
        const res = this.resource as unknown as Record<string, unknown>
        return [
            ...validateRequired(res, profileName, "url"),
            ...validateFixedValue(res, profileName, "url", "http://hl7.org/fhir/StructureDefinition/patient-birthTime"),
            ...validateChoiceRequired(res, profileName, ["valueDateTime"]),
        ]
    }

}

