// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-nationality (pkg: hl7.fhir.r4.core#4.0.1)
export class patient_nationalityProfile {
    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : patient_nationalityProfile {
        return new patient_nationalityProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-nationality",
        } as Extension
        return resource
    }

    static create () : patient_nationalityProfile {
        return patient_nationalityProfile.from(patient_nationalityProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

}

