// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Period } from "../../hl7-fhir-r4-core/Period";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

export interface observation_vitalsigns extends Observation {
    category: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[];
    subject: Reference<"Patient">;
}

export type Observation_vitalsigns_Category_VSCatSliceInput = Omit<CodeableConcept, "coding">;

import {
    buildResource,
    ensureProfile,
    applySliceMatch,
    matchesValue,
    setArraySlice,
    getArraySlice,
    ensureSliceDefaults,
    stripMatchKeys,
    validateRequired,
    validateExcluded,
    validateFixedValue,
    validateSliceCardinality,
    validateEnum,
    validateReference,
    validateChoiceRequired,
} from "../../profile-helpers";

export type observation_vitalsignsProfileInputRaw = {
    status: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown");
    code: CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)>;
    subject: Reference<"Patient">;
    category?: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/vitalsigns (pkg: hl7.fhir.r4.core#4.0.1)
export class observation_vitalsignsProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/vitalsigns";

    private static readonly VSCatSliceMatch: Record<string, unknown> = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}};

    private resource: Observation;

    constructor (resource: Observation) {
        this.resource = resource;
    }

    static from (resource: Observation) : observation_vitalsignsProfile {
        if (!resource.meta?.profile?.includes("http://hl7.org/fhir/StructureDefinition/vitalsigns")) {
            throw new Error("observation_vitalsignsProfile: meta.profile must include http://hl7.org/fhir/StructureDefinition/vitalsigns")
        }
        const profile = new observation_vitalsignsProfile(resource);
        const errors = profile.validate();
        if (errors.length > 0) throw new Error(errors.join("; "))
        return profile;
    }

    static apply (resource: Observation) : observation_vitalsignsProfile {
        ensureProfile(resource, "http://hl7.org/fhir/StructureDefinition/vitalsigns");
        return new observation_vitalsignsProfile(resource);
    }

    static createResource (args: observation_vitalsignsProfileInputRaw) : Observation {
        const categoryWithDefaults = ensureSliceDefaults(
            [...(args.category ?? [])],
            observation_vitalsignsProfile.VSCatSliceMatch,
        );

        const resource = buildResource<Observation>( {
            resourceType: "Observation",
            category: categoryWithDefaults,
            status: args.status,
            code: args.code,
            subject: args.subject,
            meta: { profile: [observation_vitalsignsProfile.canonicalUrl] },
        })
        return resource;
    }

    static create (args: observation_vitalsignsProfileInputRaw) : observation_vitalsignsProfile {
        return observation_vitalsignsProfile.apply(observation_vitalsignsProfile.createResource(args));
    }

    toResource () : Observation {
        return this.resource;
    }

    // Field accessors
    getStatus () : ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined;
    }

    setStatus (value: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value });
        return this;
    }

    getCode () : CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined {
        return this.resource.code as CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined;
    }

    setCode (value: CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)>) : this {
        Object.assign(this.resource, { code: value });
        return this;
    }

    getSubject () : Reference<"Patient"> | undefined {
        return this.resource.subject as Reference<"Patient"> | undefined;
    }

    setSubject (value: Reference<"Patient">) : this {
        Object.assign(this.resource, { subject: value });
        return this;
    }

    getCategory () : CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined {
        return this.resource.category as CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined;
    }

    setCategory (value: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[]) : this {
        Object.assign(this.resource, { category: value });
        return this;
    }

    getEffectiveDateTime () : string | undefined {
        return this.resource.effectiveDateTime as string | undefined;
    }

    setEffectiveDateTime (value: string) : this {
        Object.assign(this.resource, { effectiveDateTime: value });
        return this;
    }

    getEffectivePeriod () : Period | undefined {
        return this.resource.effectivePeriod as Period | undefined;
    }

    setEffectivePeriod (value: Period) : this {
        Object.assign(this.resource, { effectivePeriod: value });
        return this;
    }

    // Extensions
    // Slices
    public setVSCat (input?: Observation_vitalsigns_Category_VSCatSliceInput): this {
        const match = observation_vitalsignsProfile.VSCatSliceMatch
        const value = applySliceMatch<CodeableConcept>(input ?? {}, match)
        setArraySlice(this.resource.category ??= [], match, value)
        return this
    }

    public getVSCat (): Observation_vitalsigns_Category_VSCatSliceInput | undefined {
        const match = observation_vitalsignsProfile.VSCatSliceMatch
        const item = getArraySlice(this.resource.category, match)
        if (!item) return undefined
        return stripMatchKeys<Observation_vitalsigns_Category_VSCatSliceInput>(item, ["coding"])
    }

    public getVSCatRaw (): CodeableConcept | undefined {
        const match = observation_vitalsignsProfile.VSCatSliceMatch
        const item = getArraySlice(this.resource.category, match)
        return item
    }

    // Validation
    validate(): string[] {
        const profileName = "observation-vitalsigns"
        const res = this.resource
        return [
            ...validateRequired(res, profileName, "status"),
            ...validateEnum(res, profileName, "status", ["registered","preliminary","final","amended","corrected","cancelled","entered-in-error","unknown"]),
            ...validateRequired(res, profileName, "category"),
            ...validateSliceCardinality(res, profileName, "category", {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}}, "VSCat", 1, 1),
            ...validateRequired(res, profileName, "code"),
            ...validateRequired(res, profileName, "subject"),
            ...validateReference(res, profileName, "subject", ["Patient"]),
            ...validateChoiceRequired(res, profileName, ["effectiveDateTime","effectivePeriod"]),
            ...validateReference(res, profileName, "hasMember", ["MolecularSequence","QuestionnaireResponse","Observation"]),
            ...validateReference(res, profileName, "derivedFrom", ["DocumentReference","ImagingStudy","Media","MolecularSequence","QuestionnaireResponse","Observation"]),
        ]
    }

}

