// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type UnitSupplementalSystemProfileParams = {
    valueCanonical: string;
}

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-unitSupplementalSystem (pkg: hl7.fhir.uv.sdc#3.0.0)
export class UnitSupplementalSystemProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-unitSupplementalSystem"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : UnitSupplementalSystemProfile {
        return new UnitSupplementalSystemProfile(resource)
    }

    static createResource (args: UnitSupplementalSystemProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-unitSupplementalSystem",
            valueCanonical: args.valueCanonical,
        } as unknown as Extension
        return resource
    }

    static create (args: UnitSupplementalSystemProfileParams) : UnitSupplementalSystemProfile {
        return UnitSupplementalSystemProfile.from(UnitSupplementalSystemProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueCanonical () : string | undefined {
        return this.resource.valueCanonical as string | undefined
    }

    setValueCanonical (value: string) : this {
        Object.assign(this.resource, { valueCanonical: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "UnitSupplementalSystem"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-unitSupplementalSystem", "UnitSupplementalSystem"); if (e) errors.push(e) }
        if (!(r["valueCanonical"] !== undefined)) {
            errors.push("value: at least one of valueCanonical is required")
        }
        return errors
    }

}

