// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../../hl7-fhir-r4-core/Attachment";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia (pkg: hl7.fhir.uv.sdc#3.0.0)
export class ItemAnswerMediaProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ItemAnswerMediaProfile {
        return new ItemAnswerMediaProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia",
        } as unknown as Extension
        return resource
    }

    static create () : ItemAnswerMediaProfile {
        return ItemAnswerMediaProfile.from(ItemAnswerMediaProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueAttachment () : Attachment | undefined {
        return this.resource.valueAttachment as Attachment | undefined
    }

    setValueAttachment (value: Attachment) : this {
        Object.assign(this.resource, { valueAttachment: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ItemAnswerMedia"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemAnswerMedia", "ItemAnswerMedia"); if (e) errors.push(e) }
        return errors
    }

}

