// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type LaunchContextExtensionProfileParams = {
    extension: Extension[];
}

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-launchContext (pkg: hl7.fhir.uv.sdc#3.0.0)
export class LaunchContextExtensionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-launchContext"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : LaunchContextExtensionProfile {
        return new LaunchContextExtensionProfile(resource)
    }

    static createResource (args: LaunchContextExtensionProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-launchContext",
            extension: args.extension,
        } as unknown as Extension
        return resource
    }

    static create (args: LaunchContextExtensionProfileParams) : LaunchContextExtensionProfile {
        return LaunchContextExtensionProfile.from(LaunchContextExtensionProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setName (value: Coding): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "name", valueCoding: value } as Extension)
        return this
    }

    public setType (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "type", valueCode: value } as Extension)
        return this
    }

    public setDescription (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "description", valueString: value } as Extension)
        return this
    }

    public getName (): Coding | undefined {
        const ext = this.resource.extension?.find(e => e.url === "name")
        return (ext as Record<string, unknown> | undefined)?.valueCoding as Coding | undefined
    }

    public getNameExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "name")
        return ext
    }

    public getType (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "type")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "type")
        return ext
    }

    public getDescription (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "description")
        return (ext as Record<string, unknown> | undefined)?.valueString as string | undefined
    }

    public getDescriptionExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "description")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "LaunchContextExtension"); if (e) errors.push(e) }
        { const e = validateRequired(r, "url", "LaunchContextExtension"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-launchContext", "LaunchContextExtension"); if (e) errors.push(e) }
        return errors
    }

}

