// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Parameters } from "../../hl7-fhir-r4-core/Parameters";
import type { ParametersParameter } from "../../hl7-fhir-r4-core/Parameters";

export type SDCParametersQuestionnaireProcessResponseIn_Parameter_InSliceInput = Omit<ParametersParameter, "name">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-process-response-in (pkg: hl7.fhir.uv.sdc#3.0.0)
export class SDCParametersQuestionnaireProcessResponseInProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-process-response-in"

    private resource: Parameters

    constructor (resource: Parameters) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-process-response-in")) profiles.push("http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-process-response-in")
    }

    static from (resource: Parameters) : SDCParametersQuestionnaireProcessResponseInProfile {
        return new SDCParametersQuestionnaireProcessResponseInProfile(resource)
    }

    static createResource () : Parameters {
        const resource: Parameters = {
            resourceType: "Parameters",
            meta: { profile: ["http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-process-response-in"] },
        } as unknown as Parameters
        return resource
    }

    static create () : SDCParametersQuestionnaireProcessResponseInProfile {
        return SDCParametersQuestionnaireProcessResponseInProfile.from(SDCParametersQuestionnaireProcessResponseInProfile.createResource())
    }

    toResource () : Parameters {
        return this.resource
    }

    public setIn (input?: SDCParametersQuestionnaireProcessResponseIn_Parameter_InSliceInput): this {
        const match = {"name":"in"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as ParametersParameter
        const list = (this.resource.parameter ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getIn (): SDCParametersQuestionnaireProcessResponseIn_Parameter_InSliceInput | undefined {
        const match = {"name":"in"} as Record<string, unknown>
        const list = this.resource.parameter
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["name"]) as SDCParametersQuestionnaireProcessResponseIn_Parameter_InSliceInput
    }

    public getInRaw (): ParametersParameter | undefined {
        const match = {"name":"in"} as Record<string, unknown>
        const list = this.resource.parameter
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        return errors
    }

}

