// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

export interface SDCQuestionnaireExtractStructureMap extends Questionnaire {
    url: string;
}

import { getOrCreateObjectAtPath, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type SDCQuestionnaireExtractStructureMapProfileParams = {
    url: string;
    status: ("draft" | "active" | "retired" | "unknown");
}

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-smap (pkg: hl7.fhir.uv.sdc#3.0.0)
export class SDCQuestionnaireExtractStructureMapProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-smap"

    private resource: Questionnaire

    constructor (resource: Questionnaire) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-smap")) profiles.push("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-smap")
    }

    static from (resource: Questionnaire) : SDCQuestionnaireExtractStructureMapProfile {
        return new SDCQuestionnaireExtractStructureMapProfile(resource)
    }

    static createResource (args: SDCQuestionnaireExtractStructureMapProfileParams) : Questionnaire {
        const resource: Questionnaire = {
            resourceType: "Questionnaire",
            url: args.url,
            status: args.status,
            meta: { profile: ["http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-smap"] },
        } as unknown as Questionnaire
        return resource
    }

    static create (args: SDCQuestionnaireExtractStructureMapProfileParams) : SDCQuestionnaireExtractStructureMapProfile {
        return SDCQuestionnaireExtractStructureMapProfile.from(SDCQuestionnaireExtractStructureMapProfile.createResource(args))
    }

    toResource () : Questionnaire {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    toProfile () : SDCQuestionnaireExtractStructureMap {
        return this.resource as SDCQuestionnaireExtractStructureMap
    }

    public setExtensionDesignNote (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value } as Extension)
        return this
    }

    public setExtensionTerminologyServer (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value } as Extension)
        return this
    }

    public setPerformerType (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType", valueCode: value } as Extension)
        return this
    }

    public setAssembleExpectation (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation", valueCode: value } as Extension)
        return this
    }

    public setExtensionItemDesignNote (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value } as Extension)
        return this
    }

    public setExtensionItemTerminologyServer (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value } as Extension)
        return this
    }

    public setTargetStructureMap (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-targetStructureMap", valueCanonical: value } as Extension)
        return this
    }

    public setUnit (value: Coding): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/questionnaire-unit", valueCoding: value } as Extension)
        return this
    }

    public setItemHidden (value: boolean): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden", valueBoolean: value } as Extension)
        return this
    }

    public setIsSubject (value: boolean): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-isSubject", valueBoolean: value } as Extension)
        return this
    }

    public getDesignNote (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
        return (ext as Record<string, unknown> | undefined)?.valueMarkdown as string | undefined
    }

    public getDesignNoteExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
        return ext
    }

    public getTerminologyServer (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
        return (ext as Record<string, unknown> | undefined)?.valueUrl as string | undefined
    }

    public getTerminologyServerExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
        return ext
    }

    public getPerformerType (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getPerformerTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
        return ext
    }

    public getAssembleExpectation (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getAssembleExpectationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
        return ext
    }

    public getTargetStructureMap (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-targetStructureMap")
        return (ext as Record<string, unknown> | undefined)?.valueCanonical as string | undefined
    }

    public getTargetStructureMapExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-targetStructureMap")
        return ext
    }

    public getUnit (): Coding | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-unit")
        return (ext as Record<string, unknown> | undefined)?.valueCoding as Coding | undefined
    }

    public getUnitExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-unit")
        return ext
    }

    public getItemHidden (): boolean | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden")
        return (ext as Record<string, unknown> | undefined)?.valueBoolean as boolean | undefined
    }

    public getItemHiddenExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden")
        return ext
    }

    public getIsSubject (): boolean | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-isSubject")
        return (ext as Record<string, unknown> | undefined)?.valueBoolean as boolean | undefined
    }

    public getIsSubjectExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-isSubject")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "SDCQuestionnaireExtractStructureMap"); if (e) errors.push(e) }
        { const e = validateRequired(r, "status", "SDCQuestionnaireExtractStructureMap"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["draft","active","retired","unknown"], "status", "SDCQuestionnaireExtractStructureMap"); if (e) errors.push(e) }
        return errors
    }

}

