// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeSystem } from "../../hl7-fhir-r4-core/CodeSystem";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-codesystem
export interface SDCCodeSystem extends CodeSystem {
    caseSensitive: boolean;
}

import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class SDCCodeSystemProfile {
    private resource: CodeSystem

    constructor (resource: CodeSystem) {
        this.resource = resource
    }

    toResource () : CodeSystem {
        return this.resource
    }

    toProfile () : SDCCodeSystem {
        return this.resource as SDCCodeSystem
    }

    public setStyleSensitive (value: boolean): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/rendering-styleSensitive", valueBoolean: value })
        return this
    }

    public setExtensionConceptDisplayConceptDisplayLabelRenderingStyle (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/rendering-style", valueString: value })
        return this
    }

    public setExtensionConceptDisplayConceptDisplayLabelXhtml (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/rendering-xhtml", valueString: value })
        return this
    }

    public setExtensionConceptDesignationValueConceptDisplayLabelRenderingStyle (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","designation","value"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/rendering-style", valueString: value })
        return this
    }

    public setExtensionConceptDesignationValueConceptDisplayLabelXhtml (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","designation","value"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/rendering-xhtml", valueString: value })
        return this
    }

    public getStyleSensitive (): boolean | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-styleSensitive")
        return ext?.valueBoolean
    }

    public getStyleSensitiveExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-styleSensitive")
        return ext
    }

    public getConceptDisplayLabelRenderingStyle (): string | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-style")
        return ext?.valueString
    }

    public getConceptDisplayLabelRenderingStyleExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-style")
        return ext
    }

    public getConceptDisplayLabelXhtml (): string | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-xhtml")
        return ext?.valueString
    }

    public getConceptDisplayLabelXhtmlExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["concept","display"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/rendering-xhtml")
        return ext
    }

}

