// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-modular
export interface SDCModularQuestionnaire extends Questionnaire {
    url: string;
}

import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class SDCModularQuestionnaireProfile {
    private resource: Questionnaire

    constructor (resource: Questionnaire) {
        this.resource = resource
    }

    toResource () : Questionnaire {
        return this.resource
    }

    toProfile () : SDCModularQuestionnaire {
        return this.resource as SDCModularQuestionnaire
    }

    public setExtensionDesignNote (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionTerminologyServer (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setPerformerType (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType", valueCode: value })
        return this
    }

    public setAssembleExpectation (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation", valueCode: value })
        return this
    }

    public setExtensionItemDesignNote (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionItemTerminologyServer (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setAssembleContext (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembleContext", valueString: value })
        return this
    }

    public setSubQuestionnaire (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-subQuestionnaire", valueCanonical: value })
        return this
    }

    public resetDesignNote (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetTerminologyServer (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetPerformerType (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetAssembleExpectation (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetAssembleContext (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembleContext")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetSubQuestionnaire (): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        const list = target.extension as Extension[] | undefined
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-subQuestionnaire")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public getDesignNote(raw: true): Extension | undefined
    public getDesignNote(raw?: false): string | undefined
    public getDesignNote (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueMarkdown
    }

    public getTerminologyServer(raw: true): Extension | undefined
    public getTerminologyServer(raw?: false): string | undefined
    public getTerminologyServer (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueUrl
    }

    public getPerformerType(raw: true): Extension | undefined
    public getPerformerType(raw?: false): string | undefined
    public getPerformerType (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueCode
    }

    public getAssembleExpectation(raw: true): Extension | undefined
    public getAssembleExpectation(raw?: false): string | undefined
    public getAssembleExpectation (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueCode
    }

    public getAssembleContext(raw: true): Extension | undefined
    public getAssembleContext(raw?: false): string | undefined
    public getAssembleContext (raw?: boolean): Extension | string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembleContext")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueString
    }

    public getSubQuestionnaire(raw: true): Extension | undefined
    public getSubQuestionnaire(raw?: false): string | undefined
    public getSubQuestionnaire (raw?: boolean): Extension | string | undefined {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-subQuestionnaire")
        if (!ext) return undefined
        if (raw) return ext
        return ext.valueCanonical
    }

}

