// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Parameters } from "../../hl7-fhir-r4-core/Parameters";
import type { ParametersParameter } from "../../hl7-fhir-r4-core/Parameters";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/parameters-questionnaire-next-question-out
export type SDCParametersQuestionnaireNextQuestionnaireOut_Parameter_OutSliceInput = Omit<ParametersParameter, "name">;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class SDCParametersQuestionnaireNextQuestionnaireOutProfile {
    private resource: Parameters

    constructor (resource: Parameters) {
        this.resource = resource
    }

    toResource () : Parameters {
        return this.resource
    }

    public setOut (input?: SDCParametersQuestionnaireNextQuestionnaireOut_Parameter_OutSliceInput): this {
        const match = {"name":"out"} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as ParametersParameter
        const list = (this.resource.parameter ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getOut (): SDCParametersQuestionnaireNextQuestionnaireOut_Parameter_OutSliceInput | undefined {
        const match = {"name":"out"} as Record<string, unknown>
        const list = this.resource.parameter
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["name"]) as SDCParametersQuestionnaireNextQuestionnaireOut_Parameter_OutSliceInput
    }

    public getOutRaw (): ParametersParameter | undefined {
        const match = {"name":"out"} as Record<string, unknown>
        const list = this.resource.parameter
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

}

