// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-adapt
export interface SDCQuestionnaireAdapt extends Questionnaire {
    title: string;
    derivedFrom: string[];
}

import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class SDCQuestionnaireAdaptProfile {
    private resource: Questionnaire

    constructor (resource: Questionnaire) {
        this.resource = resource
    }

    toResource () : Questionnaire {
        return this.resource
    }

    toProfile () : SDCQuestionnaireAdapt {
        return this.resource as SDCQuestionnaireAdapt
    }

    public setQuestionnaireAdaptive (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-questionnaireAdaptive", ...value })
        return this
    }

    public setHidden (value: boolean): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden", valueBoolean: value })
        return this
    }

    public getQuestionnaireAdaptive (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-questionnaireAdaptive")
    }

    public getHidden (): boolean | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden")
        return ext?.valueBoolean
    }

    public getHiddenExtension (): Extension | undefined {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        const ext = (target.extension as Extension[] | undefined)?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden")
        return ext
    }

}

