// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Duration } from "../../hl7-fhir-r4-core/Duration";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-pop-obsn
import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class SDCQuestionnairePopulateObservationProfile {
    private resource: Questionnaire

    constructor (resource?: Questionnaire) {
        this.resource = resource ?? ({ resourceType: "Questionnaire" } as Questionnaire)
    }

    toResource () : Questionnaire {
        return this.resource
    }

    public setExtensionDesignNote (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionTerminologyServer (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setPerformerType (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType", valueCode: value })
        return this
    }

    public setAssembleExpectation (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation", valueCode: value })
        return this
    }

    public setExtensionItemDesignNote (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionItemTerminologyServer (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setObservationLinkPeriod (value: Duration): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-observationLinkPeriod", valueDuration: value })
        return this
    }

    public setUnit (value: Coding): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/questionnaire-unit", valueCoding: value })
        return this
    }

    public setIsSubject (value: boolean): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = []
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-isSubject", valueBoolean: value })
        return this
    }

    public resetDesignNote (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetTerminologyServer (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetPerformerType (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetAssembleExpectation (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetObservationLinkPeriod (): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        const list = target.extension as Extension[] | undefined
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-observationLinkPeriod")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetUnit (): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        const list = target.extension as Extension[] | undefined
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/questionnaire-unit")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetIsSubject (): this {
        const target = getOrCreateObjectAtPath(this.resource as Record<string, unknown>, ["item"])
        const list = target.extension as Extension[] | undefined
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-isSubject")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

}

