// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Questionnaire } from "../../hl7-fhir-r4-core/Questionnaire";

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-adapt-srch
export interface SDCQuestionnaireAdaptSearch extends Questionnaire {
    url: string;
    title: string;
    date: string;
}

import { getOrCreateObjectAtPath } from "../../profile-helpers";

export class SDCQuestionnaireAdaptSearchProfile {
    private resource: Questionnaire

    constructor (resource: Questionnaire) {
        this.resource = resource
    }

    toResource () : Questionnaire {
        return this.resource
    }

    toProfile () : SDCQuestionnaireAdaptSearch {
        return this.resource as SDCQuestionnaireAdaptSearch
    }

    public setExtensionDesignNote (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionTerminologyServer (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setPerformerType (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType", valueCode: value })
        return this
    }

    public setAssembleExpectation (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation", valueCode: value })
        return this
    }

    public setExtensionItemDesignNote (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/StructureDefinition/designNote", valueMarkdown: value })
        return this
    }

    public setExtensionItemTerminologyServer (value: string): this {
        const target = getOrCreateObjectAtPath(this.resource as unknown as Record<string, unknown>, ["item"])
        if (!Array.isArray(target.extension)) target.extension = [] as Extension[]
        (target.extension as Extension[]).push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer", valueUrl: value })
        return this
    }

    public setAssembledFrom (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembledFrom", valueCanonical: value })
        return this
    }

    public setQuestionnaireAdaptive (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-questionnaireAdaptive", ...value })
        return this
    }

    public setSubmissionEndpoint (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-endpoint", valueUri: value })
        return this
    }

    public getDesignNote (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
        return ext?.valueMarkdown
    }

    public getDesignNoteExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/designNote")
        return ext
    }

    public getTerminologyServer (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
        return ext?.valueUrl
    }

    public getTerminologyServerExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-preferredTerminologyServer")
        return ext
    }

    public getPerformerType (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
        return ext?.valueCode
    }

    public getPerformerTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-performerType")
        return ext
    }

    public getAssembleExpectation (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
        return ext?.valueCode
    }

    public getAssembleExpectationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assemble-expectation")
        return ext
    }

    public getAssembledFrom (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembledFrom")
        return ext?.valueCanonical
    }

    public getAssembledFromExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-assembledFrom")
        return ext
    }

    public getQuestionnaireAdaptive (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-questionnaireAdaptive")
    }

    public getSubmissionEndpoint (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-endpoint")
        return ext?.valueUri
    }

    public getSubmissionEndpointExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-endpoint")
        return ext
    }

}

