// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";
import type { Task } from "../../hl7-fhir-r4-core/Task";
import type { TaskInput } from "../../hl7-fhir-r4-core/Task";
import type { TaskOutput } from "../../hl7-fhir-r4-core/Task";

export interface SDCTaskQuestionnaire extends Task {
    code: CodeableConcept<("complete-questionnaire" | "fulfill")>;
    authoredOn: string;
    requester: Reference<'Device' | 'Organization' | 'Patient' | 'Practitioner' | 'PractitionerRole' | 'RelatedPerson'>;
}

export type SDCTaskQuestionnaire_Input_QuestionnaireSliceInput = Omit<TaskInput, "type">;
export type SDCTaskQuestionnaire_Input_ResponseEndpointSliceInput = Omit<TaskInput, "type">;
export type SDCTaskQuestionnaire_Output_ResponseSliceInput = Omit<TaskOutput, "type">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type SDCTaskQuestionnaireProfileParams = {
    status: ("draft" | "requested" | "received" | "accepted" | "rejected" | "ready" | "cancelled" | "in-progress" | "on-hold" | "failed" | "completed" | "entered-in-error");
    intent: ("unknown" | "proposal" | "plan" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    code: CodeableConcept<("complete-questionnaire" | "fulfill")>;
    authoredOn: string;
    requester: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
}

// CanonicalURL: http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-task (pkg: hl7.fhir.uv.sdc#3.0.0)
export class SDCTaskQuestionnaireProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-task"

    private resource: Task

    constructor (resource: Task) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-task")) profiles.push("http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-task")
    }

    static from (resource: Task) : SDCTaskQuestionnaireProfile {
        return new SDCTaskQuestionnaireProfile(resource)
    }

    static createResource (args: SDCTaskQuestionnaireProfileParams) : Task {
        const resource: Task = {
            resourceType: "Task",
            status: args.status,
            intent: args.intent,
            code: args.code,
            authoredOn: args.authoredOn,
            requester: args.requester,
            meta: { profile: ["http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-task"] },
        } as unknown as Task
        return resource
    }

    static create (args: SDCTaskQuestionnaireProfileParams) : SDCTaskQuestionnaireProfile {
        return SDCTaskQuestionnaireProfile.from(SDCTaskQuestionnaireProfile.createResource(args))
    }

    toResource () : Task {
        return this.resource
    }

    getStatus () : ("draft" | "requested" | "received" | "accepted" | "rejected" | "ready" | "cancelled" | "in-progress" | "on-hold" | "failed" | "completed" | "entered-in-error") | undefined {
        return this.resource.status as ("draft" | "requested" | "received" | "accepted" | "rejected" | "ready" | "cancelled" | "in-progress" | "on-hold" | "failed" | "completed" | "entered-in-error") | undefined
    }

    setStatus (value: ("draft" | "requested" | "received" | "accepted" | "rejected" | "ready" | "cancelled" | "in-progress" | "on-hold" | "failed" | "completed" | "entered-in-error")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getIntent () : ("unknown" | "proposal" | "plan" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option") | undefined {
        return this.resource.intent as ("unknown" | "proposal" | "plan" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option") | undefined
    }

    setIntent (value: ("unknown" | "proposal" | "plan" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option")) : this {
        Object.assign(this.resource, { intent: value })
        return this
    }

    getCode () : CodeableConcept<("complete-questionnaire" | "fulfill")> | undefined {
        return this.resource.code as CodeableConcept<("complete-questionnaire" | "fulfill")> | undefined
    }

    setCode (value: CodeableConcept<("complete-questionnaire" | "fulfill")>) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getAuthoredOn () : string | undefined {
        return this.resource.authoredOn as string | undefined
    }

    setAuthoredOn (value: string) : this {
        Object.assign(this.resource, { authoredOn: value })
        return this
    }

    getRequester () : Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson"> | undefined {
        return this.resource.requester as Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson"> | undefined
    }

    setRequester (value: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">) : this {
        Object.assign(this.resource, { requester: value })
        return this
    }

    toProfile () : SDCTaskQuestionnaire {
        return this.resource as SDCTaskQuestionnaire
    }

    public setQuestionnaire (input?: SDCTaskQuestionnaire_Input_QuestionnaireSliceInput): this {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire"}]}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as TaskInput
        const list = (this.resource.input ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setResponseEndpoint (input?: SDCTaskQuestionnaire_Input_ResponseEndpointSliceInput): this {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"response-endpoint"}]}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as TaskInput
        const list = (this.resource.input ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setResponse (input?: SDCTaskQuestionnaire_Output_ResponseSliceInput): this {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire-response"}]}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as TaskOutput
        const list = (this.resource.output ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getQuestionnaire (): SDCTaskQuestionnaire_Input_QuestionnaireSliceInput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire"}]}} as Record<string, unknown>
        const list = this.resource.input
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["type"]) as SDCTaskQuestionnaire_Input_QuestionnaireSliceInput
    }

    public getQuestionnaireRaw (): TaskInput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire"}]}} as Record<string, unknown>
        const list = this.resource.input
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getResponseEndpoint (): SDCTaskQuestionnaire_Input_ResponseEndpointSliceInput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"response-endpoint"}]}} as Record<string, unknown>
        const list = this.resource.input
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["type"]) as SDCTaskQuestionnaire_Input_ResponseEndpointSliceInput
    }

    public getResponseEndpointRaw (): TaskInput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"response-endpoint"}]}} as Record<string, unknown>
        const list = this.resource.input
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    public getResponse (): SDCTaskQuestionnaire_Output_ResponseSliceInput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire-response"}]}} as Record<string, unknown>
        const list = this.resource.output
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["type"]) as SDCTaskQuestionnaire_Output_ResponseSliceInput
    }

    public getResponseRaw (): TaskOutput | undefined {
        const match = {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire-response"}]}} as Record<string, unknown>
        const list = this.resource.output
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "status", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["draft","requested","received","accepted","rejected","ready","cancelled","in-progress","on-hold","failed","completed","entered-in-error"], "status", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateRequired(r, "intent", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateEnum(r["intent"], ["unknown","proposal","plan","order","original-order","reflex-order","filler-order","instance-order","option"], "intent", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateRequired(r, "code", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateEnum(r["code"], ["complete-questionnaire","fulfill"], "code", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateReference(r["focus"], ["SDCQuestionnaireServiceRequest"], "focus", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateReference(r["for"], ["Resource"], "for", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateRequired(r, "authoredOn", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateRequired(r, "requester", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateReference(r["requester"], ["Device","Organization","Patient","Practitioner","PractitionerRole","RelatedPerson"], "requester", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        { const e = validateReference(r["owner"], ["CareTeam","Device","HealthcareService","Organization","Patient","Practitioner","PractitionerRole","RelatedPerson"], "owner", "SDCTaskQuestionnaire"); if (e) errors.push(e) }
        errors.push(...validateSliceCardinality(r["input"] as unknown[] | undefined, {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire"}]}}, "questionnaire", 0, 1, "SDCTaskQuestionnaire.input"))
        errors.push(...validateSliceCardinality(r["output"] as unknown[] | undefined, {"type":{"coding":[{"system":"http://hl7.org/fhir/uv/sdc/CodeSystem/temp","code":"questionnaire-response"}]}}, "response", 0, 1, "SDCTaskQuestionnaire.output"))
        return errors
    }

}

