// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Money } from "../hl7-fhir-r5-core/Money";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Money } from "../hl7-fhir-r5-core/Money";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface AccountBalance extends BackboneElement {
    aggregate?: CodeableConcept;
    amount: Money;
    estimate?: boolean;
    term?: CodeableConcept;
}

export interface AccountCoverage extends BackboneElement {
    coverage: Reference<"Coverage">;
    priority?: number;
}

export interface AccountDiagnosis extends BackboneElement {
    condition: CodeableReference;
    dateOfDiagnosis?: string;
    onAdmission?: boolean;
    packageCode?: CodeableConcept[];
    sequence?: number;
    type?: CodeableConcept[];
}

export interface AccountGuarantor extends BackboneElement {
    onHold?: boolean;
    party: Reference<"Organization" | "Patient" | "RelatedPerson">;
    period?: Period;
}

export interface AccountProcedure extends BackboneElement {
    code: CodeableReference;
    dateOfService?: string;
    device?: Reference<"Device">[];
    packageCode?: CodeableConcept[];
    sequence?: number;
    type?: CodeableConcept[];
}

export interface AccountRelatedAccount extends BackboneElement {
    account: Reference<"Account">;
    relationship?: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Account
export interface Account extends DomainResource {
    resourceType: "Account";

    balance?: AccountBalance[];
    billingStatus?: CodeableConcept;
    calculatedAt?: string;
    _calculatedAt?: Element;
    coverage?: AccountCoverage[];
    currency?: CodeableConcept;
    description?: string;
    _description?: Element;
    diagnosis?: AccountDiagnosis[];
    guarantor?: AccountGuarantor[];
    identifier?: Identifier[];
    name?: string;
    _name?: Element;
    owner?: Reference<"Organization">;
    procedure?: AccountProcedure[];
    relatedAccount?: AccountRelatedAccount[];
    servicePeriod?: Period;
    status: ("active" | "inactive" | "entered-in-error" | "on-hold" | "unknown");
    _status?: Element;
    subject?: Reference<"Device" | "HealthcareService" | "Location" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole">[];
    type?: CodeableConcept;
}
export const isAccount = (resource: unknown): resource is Account => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Account";
}
