// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from "../hl7-fhir-r5-core/Age";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { Coding } from "../hl7-fhir-r5-core/Coding";
import type { ContactDetail } from "../hl7-fhir-r5-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Dosage } from "../hl7-fhir-r5-core/Dosage";
import type { Duration } from "../hl7-fhir-r5-core/Duration";
import type { Expression } from "../hl7-fhir-r5-core/Expression";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Reference } from "../hl7-fhir-r5-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r5-core/RelatedArtifact";
import type { Timing } from "../hl7-fhir-r5-core/Timing";
import type { UsageContext } from "../hl7-fhir-r5-core/UsageContext";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Age } from "../hl7-fhir-r5-core/Age";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Coding } from "../hl7-fhir-r5-core/Coding";
export type { ContactDetail } from "../hl7-fhir-r5-core/ContactDetail";
export type { Dosage } from "../hl7-fhir-r5-core/Dosage";
export type { Duration } from "../hl7-fhir-r5-core/Duration";
export type { Expression } from "../hl7-fhir-r5-core/Expression";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Reference } from "../hl7-fhir-r5-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r5-core/RelatedArtifact";
export type { Timing } from "../hl7-fhir-r5-core/Timing";
export type { UsageContext } from "../hl7-fhir-r5-core/UsageContext";

export interface ActivityDefinitionDynamicValue extends BackboneElement {
    expression: Expression;
    path: string;
}

export interface ActivityDefinitionParticipant extends BackboneElement {
    "function"?: CodeableConcept;
    role?: CodeableConcept;
    type?: ("patient" | "practitioner" | "related-person" | "device");
    typeCanonical?: string;
    typeReference?: Reference<"CareTeam" | "Device" | "DeviceDefinition" | "Endpoint" | "Group" | "HealthcareService" | "Location" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ActivityDefinition
export interface ActivityDefinition extends DomainResource {
    resourceType: "ActivityDefinition";

    approvalDate?: string;
    _approvalDate?: Element;
    asNeededBoolean?: boolean;
    _asNeededBoolean?: Element;
    asNeededCodeableConcept?: CodeableConcept;
    author?: ContactDetail[];
    bodySite?: CodeableConcept[];
    code?: CodeableConcept;
    contact?: ContactDetail[];
    copyright?: string;
    _copyright?: Element;
    copyrightLabel?: string;
    _copyrightLabel?: Element;
    date?: string;
    _date?: Element;
    description?: string;
    _description?: Element;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    dosage?: Dosage[];
    dynamicValue?: ActivityDefinitionDynamicValue[];
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    _experimental?: Element;
    identifier?: Identifier[];
    intent?: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    _intent?: Element;
    jurisdiction?: CodeableConcept[];
    kind?: ("Appointment" | "AppointmentResponse" | "CarePlan" | "Claim" | "CommunicationRequest" | "CoverageEligibilityRequest" | "DeviceRequest" | "EnrollmentRequest" | "ImmunizationRecommendation" | "MedicationRequest" | "NutritionOrder" | "RequestOrchestration" | "ServiceRequest" | "SupplyRequest" | "Task" | "Transport" | "VisionPrescription");
    _kind?: Element;
    lastReviewDate?: string;
    _lastReviewDate?: Element;
    library?: string[];
    _library?: Element;
    location?: CodeableReference;
    name?: string;
    _name?: Element;
    observationRequirement?: string[];
    _observationRequirement?: Element;
    observationResultRequirement?: string[];
    _observationResultRequirement?: Element;
    participant?: ActivityDefinitionParticipant[];
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    productCodeableConcept?: CodeableConcept;
    productReference?: Reference<"Ingredient" | "Medication" | "Substance" | "SubstanceDefinition">;
    profile?: string;
    _profile?: Element;
    publisher?: string;
    _publisher?: Element;
    purpose?: string;
    _purpose?: Element;
    quantity?: Quantity;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    specimenRequirement?: string[];
    _specimenRequirement?: Element;
    status: ("draft" | "active" | "retired" | "unknown");
    _status?: Element;
    subjectCanonical?: string;
    _subjectCanonical?: Element;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<"AdministrableProductDefinition" | "Group" | "ManufacturedItemDefinition" | "MedicinalProductDefinition" | "PackagedProductDefinition" | "SubstanceDefinition">;
    subtitle?: string;
    _subtitle?: Element;
    timingAge?: Age;
    timingDuration?: Duration;
    timingRange?: Range;
    timingTiming?: Timing;
    title?: string;
    _title?: Element;
    topic?: CodeableConcept[];
    transform?: string;
    _transform?: Element;
    url?: string;
    _url?: Element;
    usage?: string;
    _usage?: Element;
    useContext?: UsageContext[];
    version?: string;
    _version?: Element;
    versionAlgorithmCoding?: Coding;
    versionAlgorithmString?: string;
    _versionAlgorithmString?: Element;
}
export const isActivityDefinition = (resource: unknown): resource is ActivityDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ActivityDefinition";
}
