// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r5-core/Coding";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Ratio } from "../hl7-fhir-r5-core/Ratio";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r5-core/Coding";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Ratio } from "../hl7-fhir-r5-core/Ratio";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface AuditEventAgent extends BackboneElement {
    authorization?: CodeableConcept[];
    location?: Reference<"Location">;
    networkReference?: Reference<"Endpoint">;
    networkString?: string;
    networkUri?: string;
    policy?: string[];
    requestor?: boolean;
    role?: CodeableConcept[];
    type?: CodeableConcept;
    who: Reference<"CareTeam" | "Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
}

export interface AuditEventEntity extends BackboneElement {
    agent?: AuditEventAgent[];
    detail?: AuditEventEntityDetail[];
    query?: string;
    role?: CodeableConcept;
    securityLabel?: CodeableConcept[];
    what?: Reference<"Resource">;
}

export interface AuditEventEntityDetail extends BackboneElement {
    type: CodeableConcept;
    valueBase64Binary?: string;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueDateTime?: string;
    valueInteger?: number;
    valuePeriod?: Period;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueRatio?: Ratio;
    valueString?: string;
    valueTime?: string;
}

export interface AuditEventOutcome extends BackboneElement {
    code: Coding;
    detail?: CodeableConcept[];
}

export interface AuditEventSource extends BackboneElement {
    observer: Reference<"CareTeam" | "Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    site?: Reference<"Location">;
    type?: CodeableConcept[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/AuditEvent
export interface AuditEvent extends DomainResource {
    resourceType: "AuditEvent";

    action?: ("C" | "R" | "U" | "D" | "E");
    _action?: Element;
    agent: AuditEventAgent[];
    authorization?: CodeableConcept[];
    basedOn?: Reference<"CarePlan" | "DeviceRequest" | "ImmunizationRecommendation" | "MedicationRequest" | "NutritionOrder" | "ServiceRequest" | "Task">[];
    category?: CodeableConcept[];
    code: CodeableConcept;
    encounter?: Reference<"Encounter">;
    entity?: AuditEventEntity[];
    occurredDateTime?: string;
    _occurredDateTime?: Element;
    occurredPeriod?: Period;
    outcome?: AuditEventOutcome;
    patient?: Reference<"Patient">;
    recorded: string;
    _recorded?: Element;
    severity?: string;
    _severity?: Element;
    source: AuditEventSource;
}
export const isAuditEvent = (resource: unknown): resource is AuditEvent => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "AuditEvent";
}
