// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { DataType } from "../hl7-fhir-r5-core/DataType";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { DataType } from "../hl7-fhir-r5-core/DataType";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/CodeableReference
export interface CodeableReference extends DataType {
    concept?: CodeableConcept;
    reference?: Reference;
}
