// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r5-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Reference } from "../hl7-fhir-r5-core/Reference";
import type { Timing } from "../hl7-fhir-r5-core/Timing";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Annotation } from "../hl7-fhir-r5-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Reference } from "../hl7-fhir-r5-core/Reference";
export type { Timing } from "../hl7-fhir-r5-core/Timing";

export interface DeviceRequestParameter extends BackboneElement {
    code?: CodeableConcept;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/DeviceRequest
export interface DeviceRequest extends DomainResource {
    resourceType: "DeviceRequest";

    asNeeded?: boolean;
    _asNeeded?: Element;
    asNeededFor?: CodeableConcept;
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<"Resource">[];
    code: CodeableReference;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<"Encounter">;
    groupIdentifier?: Identifier;
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<"ClaimResponse" | "Coverage">[];
    intent: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    _intent?: Element;
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    parameter?: DeviceRequestParameter[];
    performer?: CodeableReference;
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    quantity?: number;
    _quantity?: Element;
    reason?: CodeableReference[];
    relevantHistory?: Reference<"Provenance">[];
    replaces?: Reference<"DeviceRequest">[];
    requester?: Reference<"Device" | "Organization" | "Practitioner" | "PractitionerRole">;
    status?: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown");
    _status?: Element;
    subject: Reference<"Device" | "Group" | "Location" | "Patient">;
    supportingInfo?: Reference<"Resource">[];
}
export const isDeviceRequest = (resource: unknown): resource is DeviceRequest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "DeviceRequest";
}
