// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Duration } from "../hl7-fhir-r5-core/Duration";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Reference } from "../hl7-fhir-r5-core/Reference";
import type { VirtualServiceDetail } from "../hl7-fhir-r5-core/VirtualServiceDetail";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Duration } from "../hl7-fhir-r5-core/Duration";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Reference } from "../hl7-fhir-r5-core/Reference";
export type { VirtualServiceDetail } from "../hl7-fhir-r5-core/VirtualServiceDetail";

export interface EncounterAdmission extends BackboneElement {
    admitSource?: CodeableConcept;
    destination?: Reference<"Location" | "Organization">;
    dischargeDisposition?: CodeableConcept;
    origin?: Reference<"Location" | "Organization">;
    preAdmissionIdentifier?: Identifier;
    reAdmission?: CodeableConcept;
}

export interface EncounterDiagnosis extends BackboneElement {
    condition?: CodeableReference[];
    use?: CodeableConcept[];
}

export interface EncounterLocation extends BackboneElement {
    form?: CodeableConcept;
    location: Reference<"Location">;
    period?: Period;
    status?: ("planned" | "active" | "reserved" | "completed");
}

export interface EncounterParticipant extends BackboneElement {
    actor?: Reference<"Device" | "Group" | "HealthcareService" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    period?: Period;
    type?: CodeableConcept[];
}

export interface EncounterReason extends BackboneElement {
    use?: CodeableConcept[];
    value?: CodeableReference[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Encounter
export interface Encounter extends DomainResource {
    resourceType: "Encounter";

    account?: Reference<"Account">[];
    actualPeriod?: Period;
    admission?: EncounterAdmission;
    appointment?: Reference<"Appointment">[];
    basedOn?: Reference<"CarePlan" | "DeviceRequest" | "MedicationRequest" | "ServiceRequest">[];
    careTeam?: Reference<"CareTeam">[];
    "class"?: CodeableConcept[];
    diagnosis?: EncounterDiagnosis[];
    dietPreference?: CodeableConcept[];
    episodeOfCare?: Reference<"EpisodeOfCare">[];
    identifier?: Identifier[];
    length?: Duration;
    location?: EncounterLocation[];
    participant?: EncounterParticipant[];
    partOf?: Reference<"Encounter">;
    plannedEndDate?: string;
    _plannedEndDate?: Element;
    plannedStartDate?: string;
    _plannedStartDate?: Element;
    priority?: CodeableConcept;
    reason?: EncounterReason[];
    serviceProvider?: Reference<"Organization">;
    serviceType?: CodeableReference[];
    specialArrangement?: CodeableConcept[];
    specialCourtesy?: CodeableConcept[];
    status: ("planned" | "arrived" | "triaged" | "in-progress" | "onleave" | "finished" | "cancelled" | "entered-in-error" | "unknown");
    _status?: Element;
    subject?: Reference<"Group" | "Patient">;
    subjectStatus?: CodeableConcept;
    type?: CodeableConcept[];
    virtualService?: VirtualServiceDetail[];
}
export const isEncounter = (resource: unknown): resource is Encounter => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Encounter";
}
