// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Base } from "../hl7-fhir-r5-core/Base";

export type { Base } from "../hl7-fhir-r5-core/Base";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Event
export interface Event extends Base {
    resourceType: "Event";

}
export const isEvent = (resource: unknown): resource is Event => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Event";
}
