// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Address } from "../hl7-fhir-r5-core/Address";
import type { Annotation } from "../hl7-fhir-r5-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r5-core/Coding";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Duration } from "../hl7-fhir-r5-core/Duration";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Ratio } from "../hl7-fhir-r5-core/Ratio";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Address } from "../hl7-fhir-r5-core/Address";
export type { Annotation } from "../hl7-fhir-r5-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r5-core/Coding";
export type { Duration } from "../hl7-fhir-r5-core/Duration";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Ratio } from "../hl7-fhir-r5-core/Ratio";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface InventoryItemAssociation extends BackboneElement {
    associationType: CodeableConcept;
    quantity: Ratio;
    relatedItem: Reference<"BiologicallyDerivedProduct" | "Device" | "DeviceDefinition" | "InventoryItem" | "Medication" | "MedicationKnowledge" | "NutritionProduct">;
}

export interface InventoryItemCharacteristic extends BackboneElement {
    characteristicType: CodeableConcept;
    valueAddress?: Address;
    valueAnnotation?: Annotation;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueDateTime?: string;
    valueDecimal?: number;
    valueDuration?: Duration;
    valueInteger?: number;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueRatio?: Ratio;
    valueString?: string;
    valueUrl?: string;
}

export interface InventoryItemDescription extends BackboneElement {
    description?: string;
    language?: ("ar" | "bg" | "bg-BG" | "bn" | "cs" | "cs-CZ" | "bs" | "bs-BA" | "da" | "da-DK" | "de" | "de-AT" | "de-CH" | "de-DE" | "el" | "el-GR" | "en" | "en-AU" | "en-CA" | "en-GB" | "en-IN" | "en-NZ" | "en-SG" | "en-US" | "es" | "es-AR" | "es-ES" | "es-UY" | "et" | "et-EE" | "fi" | "fr" | "fr-BE" | "fr-CH" | "fr-FR" | "fi-FI" | "fr-CA" | "fy" | "fy-NL" | "hi" | "hr" | "hr-HR" | "is" | "is-IS" | "it" | "it-CH" | "it-IT" | "ja" | "ko" | "lt" | "lt-LT" | "lv" | "lv-LV" | "nl" | "nl-BE" | "nl-NL" | "no" | "no-NO" | "pa" | "pl" | "pl-PL" | "pt" | "pt-PT" | "pt-BR" | "ro" | "ro-RO" | "ru" | "ru-RU" | "sk" | "sk-SK" | "sl" | "sl-SI" | "sr" | "sr-RS" | "sv" | "sv-SE" | "te" | "zh" | "zh-CN" | "zh-HK" | "zh-SG" | "zh-TW");
}

export interface InventoryItemInstance extends BackboneElement {
    expiry?: string;
    identifier?: Identifier[];
    location?: Reference<"Location">;
    lotNumber?: string;
    subject?: Reference<"Organization" | "Patient">;
}

export interface InventoryItemName extends BackboneElement {
    language: ("ar" | "bg" | "bg-BG" | "bn" | "cs" | "cs-CZ" | "bs" | "bs-BA" | "da" | "da-DK" | "de" | "de-AT" | "de-CH" | "de-DE" | "el" | "el-GR" | "en" | "en-AU" | "en-CA" | "en-GB" | "en-IN" | "en-NZ" | "en-SG" | "en-US" | "es" | "es-AR" | "es-ES" | "es-UY" | "et" | "et-EE" | "fi" | "fr" | "fr-BE" | "fr-CH" | "fr-FR" | "fi-FI" | "fr-CA" | "fy" | "fy-NL" | "hi" | "hr" | "hr-HR" | "is" | "is-IS" | "it" | "it-CH" | "it-IT" | "ja" | "ko" | "lt" | "lt-LT" | "lv" | "lv-LV" | "nl" | "nl-BE" | "nl-NL" | "no" | "no-NO" | "pa" | "pl" | "pl-PL" | "pt" | "pt-PT" | "pt-BR" | "ro" | "ro-RO" | "ru" | "ru-RU" | "sk" | "sk-SK" | "sl" | "sl-SI" | "sr" | "sr-RS" | "sv" | "sv-SE" | "te" | "zh" | "zh-CN" | "zh-HK" | "zh-SG" | "zh-TW");
    name: string;
    nameType: Coding;
}

export interface InventoryItemResponsibleOrganization extends BackboneElement {
    organization: Reference<"Organization">;
    role: CodeableConcept;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/InventoryItem
export interface InventoryItem extends DomainResource {
    resourceType: "InventoryItem";

    association?: InventoryItemAssociation[];
    baseUnit?: CodeableConcept;
    category?: CodeableConcept[];
    characteristic?: InventoryItemCharacteristic[];
    code?: CodeableConcept[];
    description?: InventoryItemDescription;
    identifier?: Identifier[];
    instance?: InventoryItemInstance;
    inventoryStatus?: CodeableConcept[];
    name?: InventoryItemName[];
    netContent?: Quantity;
    productReference?: Reference<"BiologicallyDerivedProduct" | "Device" | "Medication" | "NutritionProduct">;
    responsibleOrganization?: InventoryItemResponsibleOrganization[];
    status: string;
    _status?: Element;
}
export const isInventoryItem = (resource: unknown): resource is InventoryItem => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "InventoryItem";
}
