// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r5-core/Annotation";
import type { Attachment } from "../hl7-fhir-r5-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Dosage } from "../hl7-fhir-r5-core/Dosage";
import type { Duration } from "../hl7-fhir-r5-core/Duration";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Money } from "../hl7-fhir-r5-core/Money";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Ratio } from "../hl7-fhir-r5-core/Ratio";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Annotation } from "../hl7-fhir-r5-core/Annotation";
export type { Attachment } from "../hl7-fhir-r5-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Dosage } from "../hl7-fhir-r5-core/Dosage";
export type { Duration } from "../hl7-fhir-r5-core/Duration";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Money } from "../hl7-fhir-r5-core/Money";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Ratio } from "../hl7-fhir-r5-core/Ratio";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface MedicationKnowledgeCost extends BackboneElement {
    costCodeableConcept?: CodeableConcept;
    costMoney?: Money;
    effectiveDate?: Period[];
    source?: string;
    type: CodeableConcept;
}

export interface MedicationKnowledgeDefinitional extends BackboneElement {
    definition?: Reference<"MedicinalProductDefinition">[];
    doseForm?: CodeableConcept;
    drugCharacteristic?: MedicationKnowledgeDefinitionalDrugCharacteristic[];
    ingredient?: MedicationKnowledgeDefinitionalIngredient[];
    intendedRoute?: CodeableConcept[];
}

export interface MedicationKnowledgeDefinitionalDrugCharacteristic extends BackboneElement {
    type?: CodeableConcept;
    valueAttachment?: Attachment;
    valueBase64Binary?: string;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueString?: string;
}

export interface MedicationKnowledgeDefinitionalIngredient extends BackboneElement {
    item: CodeableReference;
    strengthCodeableConcept?: CodeableConcept;
    strengthQuantity?: Quantity;
    strengthRatio?: Ratio;
    type?: CodeableConcept;
}

export interface MedicationKnowledgeIndicationGuideline extends BackboneElement {
    dosingGuideline?: MedicationKnowledgeIndicationGuidelineDosingGuideline[];
    indication?: CodeableReference[];
}

export interface MedicationKnowledgeIndicationGuidelineDosingGuideline extends BackboneElement {
    administrationTreatment?: CodeableConcept;
    dosage?: MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage[];
    patientCharacteristic?: MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic[];
    treatmentIntent?: CodeableConcept;
}

export interface MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage extends BackboneElement {
    dosage: Dosage[];
    type: CodeableConcept;
}

export interface MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic extends BackboneElement {
    type: CodeableConcept;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

export interface MedicationKnowledgeMedicineClassification extends BackboneElement {
    classification?: CodeableConcept[];
    sourceString?: string;
    sourceUri?: string;
    type: CodeableConcept;
}

export interface MedicationKnowledgeMonitoringProgram extends BackboneElement {
    name?: string;
    type?: CodeableConcept;
}

export interface MedicationKnowledgeMonograph extends BackboneElement {
    source?: Reference<"DocumentReference">;
    type?: CodeableConcept;
}

export interface MedicationKnowledgePackaging extends BackboneElement {
    cost?: MedicationKnowledgeCost[];
    packagedProduct?: Reference<"PackagedProductDefinition">;
}

export interface MedicationKnowledgeRegulatory extends BackboneElement {
    maxDispense?: MedicationKnowledgeRegulatoryMaxDispense;
    regulatoryAuthority: Reference<"Organization">;
    schedule?: CodeableConcept[];
    substitution?: MedicationKnowledgeRegulatorySubstitution[];
}

export interface MedicationKnowledgeRegulatoryMaxDispense extends BackboneElement {
    period?: Duration;
    quantity: Quantity;
}

export interface MedicationKnowledgeRegulatorySubstitution extends BackboneElement {
    allowed: boolean;
    type: CodeableConcept;
}

export interface MedicationKnowledgeRelatedMedicationKnowledge extends BackboneElement {
    reference: Reference<"MedicationKnowledge">[];
    type: CodeableConcept;
}

export interface MedicationKnowledgeStorageGuideline extends BackboneElement {
    environmentalSetting?: MedicationKnowledgeStorageGuidelineEnvironmentalSetting[];
    note?: Annotation[];
    reference?: string;
    stabilityDuration?: Duration;
}

export interface MedicationKnowledgeStorageGuidelineEnvironmentalSetting extends BackboneElement {
    type: CodeableConcept;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueRange?: Range;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MedicationKnowledge
export interface MedicationKnowledge extends DomainResource {
    resourceType: "MedicationKnowledge";

    associatedMedication?: Reference<"Medication">[];
    author?: Reference<"Organization">;
    clinicalUseIssue?: Reference<"ClinicalUseDefinition">[];
    code?: CodeableConcept;
    cost?: MedicationKnowledgeCost[];
    definitional?: MedicationKnowledgeDefinitional;
    identifier?: Identifier[];
    indicationGuideline?: MedicationKnowledgeIndicationGuideline[];
    intendedJurisdiction?: CodeableConcept[];
    medicineClassification?: MedicationKnowledgeMedicineClassification[];
    monitoringProgram?: MedicationKnowledgeMonitoringProgram[];
    monograph?: MedicationKnowledgeMonograph[];
    name?: string[];
    _name?: Element;
    packaging?: MedicationKnowledgePackaging[];
    preparationInstruction?: string;
    _preparationInstruction?: Element;
    productType?: CodeableConcept[];
    regulatory?: MedicationKnowledgeRegulatory[];
    relatedMedicationKnowledge?: MedicationKnowledgeRelatedMedicationKnowledge[];
    status?: string;
    _status?: Element;
    storageGuideline?: MedicationKnowledgeStorageGuideline[];
}
export const isMedicationKnowledge = (resource: unknown): resource is MedicationKnowledge => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MedicationKnowledge";
}
