// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r5-core/Annotation";
import type { Attachment } from "../hl7-fhir-r5-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Ratio } from "../hl7-fhir-r5-core/Ratio";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Annotation } from "../hl7-fhir-r5-core/Annotation";
export type { Attachment } from "../hl7-fhir-r5-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Ratio } from "../hl7-fhir-r5-core/Ratio";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface NutritionProductCharacteristic extends BackboneElement {
    type: CodeableConcept;
    valueAttachment?: Attachment;
    valueBase64Binary?: string;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueQuantity?: Quantity;
    valueString?: string;
}

export interface NutritionProductIngredient extends BackboneElement {
    amount?: Ratio[];
    item: CodeableReference;
}

export interface NutritionProductInstance extends BackboneElement {
    biologicalSourceEvent?: Identifier;
    expiry?: string;
    identifier?: Identifier[];
    lotNumber?: string;
    name?: string;
    quantity?: Quantity;
    useBy?: string;
}

export interface NutritionProductNutrient extends BackboneElement {
    amount?: Ratio[];
    item?: CodeableReference;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/NutritionProduct
export interface NutritionProduct extends DomainResource {
    resourceType: "NutritionProduct";

    category?: CodeableConcept[];
    characteristic?: NutritionProductCharacteristic[];
    code?: CodeableConcept;
    ingredient?: NutritionProductIngredient[];
    instance?: NutritionProductInstance[];
    knownAllergen?: CodeableReference[];
    manufacturer?: Reference<"Organization">[];
    note?: Annotation[];
    nutrient?: NutritionProductNutrient[];
    status: string;
    _status?: Element;
}
export const isNutritionProduct = (resource: unknown): resource is NutritionProduct => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "NutritionProduct";
}
