// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { ExtendedContactDetail } from "../hl7-fhir-r5-core/ExtendedContactDetail";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { ExtendedContactDetail } from "../hl7-fhir-r5-core/ExtendedContactDetail";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/OrganizationAffiliation
export interface OrganizationAffiliation extends DomainResource {
    resourceType: "OrganizationAffiliation";

    active?: boolean;
    _active?: Element;
    code?: CodeableConcept[];
    contact?: ExtendedContactDetail[];
    endpoint?: Reference<"Endpoint">[];
    healthcareService?: Reference<"HealthcareService">[];
    identifier?: Identifier[];
    location?: Reference<"Location">[];
    network?: Reference<"Organization">[];
    organization?: Reference<"Organization">;
    participatingOrganization?: Reference<"Organization">;
    period?: Period;
    specialty?: CodeableConcept[];
}
export const isOrganizationAffiliation = (resource: unknown): resource is OrganizationAffiliation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "OrganizationAffiliation";
}
