// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r5-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { MarketingStatus } from "../hl7-fhir-r5-core/MarketingStatus";
import type { ProductShelfLife } from "../hl7-fhir-r5-core/ProductShelfLife";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Attachment } from "../hl7-fhir-r5-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { MarketingStatus } from "../hl7-fhir-r5-core/MarketingStatus";
export type { ProductShelfLife } from "../hl7-fhir-r5-core/ProductShelfLife";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface PackagedProductDefinitionLegalStatusOfSupply extends BackboneElement {
    code?: CodeableConcept;
    jurisdiction?: CodeableConcept;
}

export interface PackagedProductDefinitionPackaging extends BackboneElement {
    alternateMaterial?: CodeableConcept[];
    componentPart?: boolean;
    containedItem?: PackagedProductDefinitionPackagingContainedItem[];
    identifier?: Identifier[];
    manufacturer?: Reference<"Organization">[];
    material?: CodeableConcept[];
    packaging?: PackagedProductDefinitionPackaging[];
    property?: PackagedProductDefinitionPackagingProperty[];
    quantity?: number;
    shelfLifeStorage?: ProductShelfLife[];
    type?: CodeableConcept;
}

export interface PackagedProductDefinitionPackagingContainedItem extends BackboneElement {
    amount?: Quantity;
    item: CodeableReference;
}

export interface PackagedProductDefinitionPackagingProperty extends BackboneElement {
    type: CodeableConcept;
    valueAttachment?: Attachment;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valueDate?: string;
    valueQuantity?: Quantity;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/PackagedProductDefinition
export interface PackagedProductDefinition extends DomainResource {
    resourceType: "PackagedProductDefinition";

    attachedDocument?: Reference<"DocumentReference">[];
    characteristic?: PackagedProductDefinitionPackagingProperty[];
    containedItemQuantity?: Quantity[];
    copackagedIndicator?: boolean;
    _copackagedIndicator?: Element;
    description?: string;
    _description?: Element;
    identifier?: Identifier[];
    legalStatusOfSupply?: PackagedProductDefinitionLegalStatusOfSupply[];
    manufacturer?: Reference<"Organization">[];
    marketingStatus?: MarketingStatus[];
    name?: string;
    _name?: Element;
    packageFor?: Reference<"MedicinalProductDefinition">[];
    packaging?: PackagedProductDefinitionPackaging;
    status?: CodeableConcept;
    statusDate?: string;
    _statusDate?: Element;
    type?: CodeableConcept;
}
export const isPackagedProductDefinition = (resource: unknown): resource is PackagedProductDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "PackagedProductDefinition";
}
