// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Money } from "../hl7-fhir-r5-core/Money";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Money } from "../hl7-fhir-r5-core/Money";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

export interface PaymentReconciliationAllocation extends BackboneElement {
    account?: Reference<"Account">;
    amount?: Money;
    date?: string;
    encounter?: Reference<"Encounter">;
    identifier?: Identifier;
    payee?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    predecessor?: Identifier;
    response?: Reference<"ClaimResponse">;
    responsible?: Reference<"PractitionerRole">;
    submitter?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    target?: Reference<"Account" | "ChargeItem" | "Claim" | "Contract" | "Encounter" | "Invoice">;
    targetItemIdentifier?: Identifier;
    targetItemPositiveInt?: number;
    targetItemString?: string;
    type?: CodeableConcept;
}

export interface PaymentReconciliationProcessNote extends BackboneElement {
    text?: string;
    type?: ("display" | "print" | "printoper");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/PaymentReconciliation
export interface PaymentReconciliation extends DomainResource {
    resourceType: "PaymentReconciliation";

    accountNumber?: string;
    _accountNumber?: Element;
    allocation?: PaymentReconciliationAllocation[];
    amount: Money;
    authorization?: string;
    _authorization?: Element;
    cardBrand?: string;
    _cardBrand?: Element;
    created: string;
    _created?: Element;
    date: string;
    _date?: Element;
    disposition?: string;
    _disposition?: Element;
    enterer?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    expirationDate?: string;
    _expirationDate?: Element;
    formCode?: CodeableConcept;
    identifier?: Identifier[];
    issuerType?: CodeableConcept;
    kind?: CodeableConcept;
    location?: Reference<"Location">;
    method?: CodeableConcept;
    outcome?: string;
    _outcome?: Element;
    paymentIdentifier?: Identifier;
    paymentIssuer?: Reference<"Organization" | "Patient" | "RelatedPerson">;
    period?: Period;
    processNote?: PaymentReconciliationProcessNote[];
    processor?: string;
    _processor?: Element;
    referenceNumber?: string;
    _referenceNumber?: Element;
    request?: Reference<"Task">;
    requestor?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    returnedAmount?: Money;
    status: ("active" | "cancelled" | "draft" | "entered-in-error");
    _status?: Element;
    tenderedAmount?: Money;
    type: CodeableConcept;
}
export const isPaymentReconciliation = (resource: unknown): resource is PaymentReconciliation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "PaymentReconciliation";
}
