// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r5-core/Attachment";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { DataType } from "../hl7-fhir-r5-core/DataType";
import type { Reference } from "../hl7-fhir-r5-core/Reference";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Attachment } from "../hl7-fhir-r5-core/Attachment";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { DataType } from "../hl7-fhir-r5-core/DataType";
export type { Reference } from "../hl7-fhir-r5-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/RelatedArtifact
export interface RelatedArtifact extends DataType {
    citation?: string;
    _citation?: Element;
    classifier?: CodeableConcept[];
    display?: string;
    _display?: Element;
    document?: Attachment;
    label?: string;
    _label?: Element;
    publicationDate?: string;
    _publicationDate?: Element;
    publicationStatus?: ("draft" | "active" | "retired" | "unknown");
    _publicationStatus?: Element;
    resource?: string;
    _resource?: Element;
    resourceReference?: Reference<"Resource">;
    type: ("documentation" | "justification" | "citation" | "predecessor" | "successor" | "derived-from" | "depends-on" | "composed-of");
    _type?: Element;
}
