// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r5-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
import type { DomainResource } from "../hl7-fhir-r5-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r5-core/Identifier";
import type { Period } from "../hl7-fhir-r5-core/Period";
import type { Quantity } from "../hl7-fhir-r5-core/Quantity";
import type { Range } from "../hl7-fhir-r5-core/Range";
import type { Ratio } from "../hl7-fhir-r5-core/Ratio";
import type { Reference } from "../hl7-fhir-r5-core/Reference";
import type { Timing } from "../hl7-fhir-r5-core/Timing";

import type { Element } from "../hl7-fhir-r5-core/Element";
export type { Annotation } from "../hl7-fhir-r5-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r5-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r5-core/CodeableConcept";
export type { CodeableReference } from "../hl7-fhir-r5-core/CodeableReference";
export type { Identifier } from "../hl7-fhir-r5-core/Identifier";
export type { Period } from "../hl7-fhir-r5-core/Period";
export type { Quantity } from "../hl7-fhir-r5-core/Quantity";
export type { Range } from "../hl7-fhir-r5-core/Range";
export type { Ratio } from "../hl7-fhir-r5-core/Ratio";
export type { Reference } from "../hl7-fhir-r5-core/Reference";
export type { Timing } from "../hl7-fhir-r5-core/Timing";

export interface ServiceRequestOrderDetail extends BackboneElement {
    parameter: ServiceRequestOrderDetailParameter[];
    parameterFocus?: CodeableReference;
}

export interface ServiceRequestOrderDetailParameter extends BackboneElement {
    code: CodeableConcept;
    valueBoolean?: boolean;
    valueCodeableConcept?: CodeableConcept;
    valuePeriod?: Period;
    valueQuantity?: Quantity;
    valueRange?: Range;
    valueRatio?: Ratio;
    valueString?: string;
}

export interface ServiceRequestPatientInstruction extends BackboneElement {
    instructionMarkdown?: string;
    instructionReference?: Reference<"DocumentReference">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ServiceRequest
export interface ServiceRequest extends DomainResource {
    resourceType: "ServiceRequest";

    asNeededBoolean?: boolean;
    _asNeededBoolean?: Element;
    asNeededCodeableConcept?: CodeableConcept;
    authoredOn?: string;
    _authoredOn?: Element;
    basedOn?: Reference<"CarePlan" | "MedicationRequest" | "ServiceRequest">[];
    bodySite?: CodeableConcept[];
    bodyStructure?: Reference<"BodyStructure">;
    category?: CodeableConcept[];
    code?: CodeableReference;
    doNotPerform?: boolean;
    _doNotPerform?: Element;
    encounter?: Reference<"Encounter">;
    focus?: Reference<"Resource">[];
    identifier?: Identifier[];
    instantiatesCanonical?: string[];
    _instantiatesCanonical?: Element;
    instantiatesUri?: string[];
    _instantiatesUri?: Element;
    insurance?: Reference<"ClaimResponse" | "Coverage">[];
    intent: ("proposal" | "plan" | "directive" | "order" | "original-order" | "reflex-order" | "filler-order" | "instance-order" | "option");
    _intent?: Element;
    location?: CodeableReference[];
    note?: Annotation[];
    occurrenceDateTime?: string;
    _occurrenceDateTime?: Element;
    occurrencePeriod?: Period;
    occurrenceTiming?: Timing;
    orderDetail?: ServiceRequestOrderDetail[];
    patientInstruction?: ServiceRequestPatientInstruction[];
    performer?: Reference<"CareTeam" | "Device" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    performerType?: CodeableConcept;
    priority?: ("routine" | "urgent" | "asap" | "stat");
    _priority?: Element;
    quantityQuantity?: Quantity;
    quantityRange?: Range;
    quantityRatio?: Ratio;
    reason?: CodeableReference[];
    relevantHistory?: Reference<"Provenance">[];
    replaces?: Reference<"ServiceRequest">[];
    requester?: Reference<"Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    requisition?: Identifier;
    specimen?: Reference<"Specimen">[];
    status: ("draft" | "active" | "on-hold" | "revoked" | "completed" | "entered-in-error" | "unknown");
    _status?: Element;
    subject: Reference<"Device" | "Group" | "Location" | "Patient">;
    supportingInfo?: CodeableReference[];
}
export const isServiceRequest = (resource: unknown): resource is ServiceRequest => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ServiceRequest";
}
