// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-examples/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type concept_commentsProfileParams = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/valueset-concept-comments (pkg: hl7.fhir.r4.examples#4.0.1)
export class concept_commentsProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : concept_commentsProfile {
        return new concept_commentsProfile(resource)
    }

    static createResource (args: concept_commentsProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments",
            valueString: args.valueString,
        } as unknown as Extension
        return resource
    }

    static create (args: concept_commentsProfileParams) : concept_commentsProfile {
        return concept_commentsProfile.from(concept_commentsProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "concept-comments"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments", "concept-comments"); if (e) errors.push(e) }
        if (!(r["valueString"] !== undefined)) {
            errors.push("value: at least one of valueString is required")
        }
        return errors
    }

}

