// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-examples/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type exposureDateProfileParams = {
    valueDateTime: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/openEHR-exposureDate (pkg: hl7.fhir.r4.examples#4.0.1)
export class exposureDateProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDate"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : exposureDateProfile {
        return new exposureDateProfile(resource)
    }

    static createResource (args: exposureDateProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDate",
            valueDateTime: args.valueDateTime,
        } as unknown as Extension
        return resource
    }

    static create (args: exposureDateProfileParams) : exposureDateProfile {
        return exposureDateProfile.from(exposureDateProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "exposureDate"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDate", "exposureDate"); if (e) errors.push(e) }
        if (!(r["valueDateTime"] !== undefined)) {
            errors.push("value: at least one of valueDateTime is required")
        }
        return errors
    }

}

