// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Group } from "../../hl7-fhir-r4-examples/Group";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/actualgroup (pkg: hl7.fhir.r4.examples#4.0.1)
export class Actual_GroupProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/actualgroup"

    private resource: Group

    constructor (resource: Group) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/actualgroup")) profiles.push("http://hl7.org/fhir/StructureDefinition/actualgroup")
    }

    static from (resource: Group) : Actual_GroupProfile {
        return new Actual_GroupProfile(resource)
    }

    static createResource () : Group {
        const resource: Group = {
            resourceType: "Group",
            actual: true,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/actualgroup"] },
        } as unknown as Group
        return resource
    }

    static create () : Actual_GroupProfile {
        return Actual_GroupProfile.from(Actual_GroupProfile.createResource())
    }

    toResource () : Group {
        return this.resource
    }

    getActual () : boolean | undefined {
        return this.resource.actual as boolean | undefined
    }

    setActual (value: boolean) : this {
        Object.assign(this.resource, { actual: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "actual", "Actual Group"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "actual", true, "Actual Group"); if (e) errors.push(e) }
        return errors
    }

}

