// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-examples/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-examples/Observation";
import type { Period } from "../../hl7-fhir-r4-examples/Period";
import type { Quantity } from "../../hl7-fhir-r4-examples/Quantity";
import type { Reference } from "../../hl7-fhir-r4-examples/Reference";

export interface observation_bmi extends Observation {
    category: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[];
    subject: Reference<"Patient">;
    valueQuantity: Quantity;
}

export type Observation_bmi_Category_VSCatSliceInput = Omit<CodeableConcept, "coding">;

import { applySliceMatch, matchesSlice, extractSliceSimplified, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type observation_bmiProfileParams = {
    status: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown");
    subject: Reference<"Patient">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/bmi (pkg: hl7.fhir.r4.examples#4.0.1)
export class observation_bmiProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/bmi"

    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/bmi")) profiles.push("http://hl7.org/fhir/StructureDefinition/bmi")
    }

    static from (resource: Observation) : observation_bmiProfile {
        return new observation_bmiProfile(resource)
    }

    static createResource (args: observation_bmiProfileParams) : Observation {
        const resource: Observation = {
            resourceType: "Observation",
            category: [{"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}}],
            code: {"coding":[{"code":"39156-5","system":"http://loinc.org"}]},
            status: args.status,
            subject: args.subject,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/bmi"] },
        } as unknown as Observation
        return resource
    }

    static create (args: observation_bmiProfileParams) : observation_bmiProfile {
        return observation_bmiProfile.from(observation_bmiProfile.createResource(args))
    }

    toResource () : Observation {
        return this.resource
    }

    getStatus () : ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined
    }

    setStatus (value: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getSubject () : Reference<"Patient"> | undefined {
        return this.resource.subject as Reference<"Patient"> | undefined
    }

    setSubject (value: Reference<"Patient">) : this {
        Object.assign(this.resource, { subject: value })
        return this
    }

    getCategory () : CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined {
        return this.resource.category as CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[] | undefined
    }

    setCategory (value: CodeableConcept<("social-history" | "vital-signs" | "imaging" | "laboratory" | "procedure" | "survey" | "exam" | "therapy" | "activity" | string)>[]) : this {
        Object.assign(this.resource, { category: value })
        return this
    }

    getCode () : CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined {
        return this.resource.code as CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)> | undefined
    }

    setCode (value: CodeableConcept<("85353-1" | "9279-1" | "8867-4" | "2708-6" | "8310-5" | "8302-2" | "9843-4" | "29463-7" | "39156-5" | "85354-9" | "8480-6" | "8462-4" | "8478-0" | string)>) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getEffectiveDateTime () : string | undefined {
        return this.resource.effectiveDateTime as string | undefined
    }

    setEffectiveDateTime (value: string) : this {
        Object.assign(this.resource, { effectiveDateTime: value })
        return this
    }

    getEffectivePeriod () : Period | undefined {
        return this.resource.effectivePeriod as Period | undefined
    }

    setEffectivePeriod (value: Period) : this {
        Object.assign(this.resource, { effectivePeriod: value })
        return this
    }

    getValueQuantity () : Quantity | undefined {
        return this.resource.valueQuantity as Quantity | undefined
    }

    setValueQuantity (value: Quantity) : this {
        Object.assign(this.resource, { valueQuantity: value })
        return this
    }

    toProfile () : observation_bmi {
        return this.resource as observation_bmi
    }

    public setVscat (input?: Observation_bmi_Category_VSCatSliceInput): this {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const value = applySliceMatch((input ?? {}) as Record<string, unknown>, match) as unknown as CodeableConcept
        const list = (this.resource.category ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public getVscat (): Observation_bmi_Category_VSCatSliceInput | undefined {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["coding"]) as Observation_bmi_Category_VSCatSliceInput
    }

    public getVscatRaw (): CodeableConcept | undefined {
        const match = {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}} as Record<string, unknown>
        const list = this.resource.category
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        return item
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "status", "observation-bmi"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["registered","preliminary","final","amended","corrected","cancelled","entered-in-error","unknown"], "status", "observation-bmi"); if (e) errors.push(e) }
        { const e = validateRequired(r, "category", "observation-bmi"); if (e) errors.push(e) }
        errors.push(...validateSliceCardinality(r["category"] as unknown[] | undefined, {"coding":{"code":"vital-signs","system":"http://terminology.hl7.org/CodeSystem/observation-category"}}, "VSCat", 1, 1, "observation-bmi.category"))
        { const e = validateRequired(r, "code", "observation-bmi"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "code", {"coding":[{"code":"39156-5","system":"http://loinc.org"}]}, "observation-bmi"); if (e) errors.push(e) }
        { const e = validateRequired(r, "subject", "observation-bmi"); if (e) errors.push(e) }
        { const e = validateReference(r["subject"], ["Patient"], "subject", "observation-bmi"); if (e) errors.push(e) }
        if (!(r["effectiveDateTime"] !== undefined || r["effectivePeriod"] !== undefined)) {
            errors.push("effective: at least one of effectiveDateTime, effectivePeriod is required")
        }
        { const e = validateReference(r["hasMember"], ["MolecularSequence","QuestionnaireResponse","observation-vitalsigns"], "hasMember", "observation-bmi"); if (e) errors.push(e) }
        { const e = validateReference(r["derivedFrom"], ["DocumentReference","ImagingStudy","Media","MolecularSequence","QuestionnaireResponse","observation-vitalsigns"], "derivedFrom", "observation-bmi"); if (e) errors.push(e) }
        return errors
    }

}

