// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r5-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { Reference } from "../../hl7-fhir-r5-core/Reference";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type GoalRelationshipProfileParams = {
    extension: Extension[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/goal-relationship (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class GoalRelationshipProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/goal-relationship"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : GoalRelationshipProfile {
        return new GoalRelationshipProfile(resource)
    }

    static createResource (args: GoalRelationshipProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/goal-relationship",
            extension: args.extension,
        } as unknown as Extension
        return resource
    }

    static create (args: GoalRelationshipProfileParams) : GoalRelationshipProfile {
        return GoalRelationshipProfile.from(GoalRelationshipProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setType (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "type", valueCodeableConcept: value } as Extension)
        return this
    }

    public setTarget (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "target", valueReference: value } as Extension)
        return this
    }

    public getType (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "type")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableConcept as CodeableConcept | undefined
    }

    public getTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "type")
        return ext
    }

    public getTarget (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "target")
        return (ext as Record<string, unknown> | undefined)?.valueReference as Reference | undefined
    }

    public getTargetExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "target")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "GoalRelationship"); if (e) errors.push(e) }
        { const e = validateRequired(r, "url", "GoalRelationship"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/goal-relationship", "GoalRelationship"); if (e) errors.push(e) }
        return errors
    }

}

