// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Age } from "../../hl7-fhir-r5-core/Age";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type AIResolutionAgeProfileParams = {
    valueAge: Age;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/allergyintolerance-resolutionAge (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class AIResolutionAgeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/allergyintolerance-resolutionAge"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : AIResolutionAgeProfile {
        return new AIResolutionAgeProfile(resource)
    }

    static createResource (args: AIResolutionAgeProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/allergyintolerance-resolutionAge",
            valueAge: args.valueAge,
        } as unknown as Extension
        return resource
    }

    static create (args: AIResolutionAgeProfileParams) : AIResolutionAgeProfile {
        return AIResolutionAgeProfile.from(AIResolutionAgeProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueAge () : Age | undefined {
        return this.resource.valueAge as Age | undefined
    }

    setValueAge (value: Age) : this {
        Object.assign(this.resource, { valueAge: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "AIResolutionAge"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/allergyintolerance-resolutionAge", "AIResolutionAge"); if (e) errors.push(e) }
        if (!(r["valueAge"] !== undefined)) {
            errors.push("value: at least one of valueAge is required")
        }
        return errors
    }

}

