// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r5-core/Coding";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/artifact-versionAlgorithm (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class ArtifactVersionAlgorithmProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/artifact-versionAlgorithm"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ArtifactVersionAlgorithmProfile {
        return new ArtifactVersionAlgorithmProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/artifact-versionAlgorithm",
        } as unknown as Extension
        return resource
    }

    static create () : ArtifactVersionAlgorithmProfile {
        return ArtifactVersionAlgorithmProfile.from(ArtifactVersionAlgorithmProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getValueCoding () : Coding | undefined {
        return this.resource.valueCoding as Coding | undefined
    }

    setValueCoding (value: Coding) : this {
        Object.assign(this.resource, { valueCoding: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ArtifactVersionAlgorithm"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/artifact-versionAlgorithm", "ArtifactVersionAlgorithm"); if (e) errors.push(e) }
        if (!(r["valueString"] !== undefined || r["valueCoding"] !== undefined)) {
            errors.push("value: at least one of valueString, valueCoding is required")
        }
        return errors
    }

}

