// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r5-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { Quantity } from "../../hl7-fhir-r5-core/Quantity";
import type { Reference } from "../../hl7-fhir-r5-core/Reference";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/medication-manufacturingBatch (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class MedManufacturingBatchProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/medication-manufacturingBatch"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : MedManufacturingBatchProfile {
        return new MedManufacturingBatchProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/medication-manufacturingBatch",
        } as unknown as Extension
        return resource
    }

    static create () : MedManufacturingBatchProfile {
        return MedManufacturingBatchProfile.from(MedManufacturingBatchProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setManufacturingDate (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "manufacturingDate", valueDateTime: value } as Extension)
        return this
    }

    public setManufacturingDateClassification (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "manufacturingDateClassification", valueCodeableConcept: value } as Extension)
        return this
    }

    public setAssignedManufacturer (value: Reference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "assignedManufacturer", valueReference: value } as Extension)
        return this
    }

    public setExpirationDateClassification (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "expirationDateClassification", valueCodeableConcept: value } as Extension)
        return this
    }

    public setBatchUtilization (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "batchUtilization", valueCodeableConcept: value } as Extension)
        return this
    }

    public setBatchQuantity (value: Quantity): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "batchQuantity", valueQuantity: value } as Extension)
        return this
    }

    public setAdditionalInformation (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "additionalInformation", valueString: value } as Extension)
        return this
    }

    public setContainer (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "container", ...value })
        return this
    }

    public getManufacturingDate (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "manufacturingDate")
        return (ext as Record<string, unknown> | undefined)?.valueDateTime as string | undefined
    }

    public getManufacturingDateExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "manufacturingDate")
        return ext
    }

    public getManufacturingDateClassification (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "manufacturingDateClassification")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableConcept as CodeableConcept | undefined
    }

    public getManufacturingDateClassificationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "manufacturingDateClassification")
        return ext
    }

    public getAssignedManufacturer (): Reference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "assignedManufacturer")
        return (ext as Record<string, unknown> | undefined)?.valueReference as Reference | undefined
    }

    public getAssignedManufacturerExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "assignedManufacturer")
        return ext
    }

    public getExpirationDateClassification (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "expirationDateClassification")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableConcept as CodeableConcept | undefined
    }

    public getExpirationDateClassificationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "expirationDateClassification")
        return ext
    }

    public getBatchUtilization (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "batchUtilization")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableConcept as CodeableConcept | undefined
    }

    public getBatchUtilizationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "batchUtilization")
        return ext
    }

    public getBatchQuantity (): Quantity | undefined {
        const ext = this.resource.extension?.find(e => e.url === "batchQuantity")
        return (ext as Record<string, unknown> | undefined)?.valueQuantity as Quantity | undefined
    }

    public getBatchQuantityExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "batchQuantity")
        return ext
    }

    public getAdditionalInformation (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "additionalInformation")
        return (ext as Record<string, unknown> | undefined)?.valueString as string | undefined
    }

    public getAdditionalInformationExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "additionalInformation")
        return ext
    }

    public getContainer (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "container")
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "MedManufacturingBatch"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/medication-manufacturingBatch", "MedManufacturingBatch"); if (e) errors.push(e) }
        return errors
    }

}

