// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type SDFhirTypeProfileParams = {
    valueUrl: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/structuredefinition-fhir-type (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class SDFhirTypeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fhir-type"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : SDFhirTypeProfile {
        return new SDFhirTypeProfile(resource)
    }

    static createResource (args: SDFhirTypeProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/structuredefinition-fhir-type",
            valueUrl: args.valueUrl,
        } as unknown as Extension
        return resource
    }

    static create (args: SDFhirTypeProfileParams) : SDFhirTypeProfile {
        return SDFhirTypeProfile.from(SDFhirTypeProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueUrl () : string | undefined {
        return this.resource.valueUrl as string | undefined
    }

    setValueUrl (value: string) : this {
        Object.assign(this.resource, { valueUrl: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "SDFhirType"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/structuredefinition-fhir-type", "SDFhirType"); if (e) errors.push(e) }
        if (!(r["valueUrl"] !== undefined)) {
            errors.push("value: at least one of valueUrl is required")
        }
        return errors
    }

}

