// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type KnowledgeRepresentationLevelProfileParams = {
    valueCode: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class KnowledgeRepresentationLevelProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : KnowledgeRepresentationLevelProfile {
        return new KnowledgeRepresentationLevelProfile(resource)
    }

    static createResource (args: KnowledgeRepresentationLevelProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel",
            valueCode: args.valueCode,
        } as unknown as Extension
        return resource
    }

    static create (args: KnowledgeRepresentationLevelProfileParams) : KnowledgeRepresentationLevelProfile {
        return KnowledgeRepresentationLevelProfile.from(KnowledgeRepresentationLevelProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueCode () : string | undefined {
        return this.resource.valueCode as string | undefined
    }

    setValueCode (value: string) : this {
        Object.assign(this.resource, { valueCode: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "KnowledgeRepresentationLevel"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel", "KnowledgeRepresentationLevel"); if (e) errors.push(e) }
        if (!(r["valueCode"] !== undefined)) {
            errors.push("value: at least one of valueCode is required")
        }
        return errors
    }

}

