// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type CSKeyWordProfileParams = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/codesystem-keyWord (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class CSKeyWordProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/codesystem-keyWord"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : CSKeyWordProfile {
        return new CSKeyWordProfile(resource)
    }

    static createResource (args: CSKeyWordProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/codesystem-keyWord",
            valueString: args.valueString,
        } as unknown as Extension
        return resource
    }

    static create (args: CSKeyWordProfileParams) : CSKeyWordProfile {
        return CSKeyWordProfile.from(CSKeyWordProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "CSKeyWord"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/codesystem-keyWord", "CSKeyWord"); if (e) errors.push(e) }
        if (!(r["valueString"] !== undefined)) {
            errors.push("value: at least one of valueString is required")
        }
        return errors
    }

}

