// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-modelInfo-isIncluded (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class ModelInfoIsIncludedProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-modelInfo-isIncluded"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ModelInfoIsIncludedProfile {
        return new ModelInfoIsIncludedProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-modelInfo-isIncluded",
        } as unknown as Extension
        return resource
    }

    static create () : ModelInfoIsIncludedProfile {
        return ModelInfoIsIncludedProfile.from(ModelInfoIsIncludedProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueBoolean () : boolean | undefined {
        return this.resource.valueBoolean as boolean | undefined
    }

    setValueBoolean (value: boolean) : this {
        Object.assign(this.resource, { valueBoolean: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ModelInfoIsIncluded"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/cqf-modelInfo-isIncluded", "ModelInfoIsIncluded"); if (e) errors.push(e) }
        return errors
    }

}

