// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { Reference } from "../../hl7-fhir-r5-core/Reference";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type DRRiskProfileParams = {
    valueReference: Reference;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/diagnosticReport-risk (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class DRRiskProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/diagnosticReport-risk"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : DRRiskProfile {
        return new DRRiskProfile(resource)
    }

    static createResource (args: DRRiskProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/diagnosticReport-risk",
            valueReference: args.valueReference,
        } as unknown as Extension
        return resource
    }

    static create (args: DRRiskProfileParams) : DRRiskProfile {
        return DRRiskProfile.from(DRRiskProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueReference () : Reference | undefined {
        return this.resource.valueReference as Reference | undefined
    }

    setValueReference (value: Reference) : this {
        Object.assign(this.resource, { valueReference: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "DRRisk"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/diagnosticReport-risk", "DRRisk"); if (e) errors.push(e) }
        if (!(r["valueReference"] !== undefined)) {
            errors.push("value: at least one of valueReference is required")
        }
        return errors
    }

}

