// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r5-core/Coding";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type PatPreferenceTypeProfileParams = {
    valueCoding: Coding;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-preferenceType (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class PatPreferenceTypeProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-preferenceType"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : PatPreferenceTypeProfile {
        return new PatPreferenceTypeProfile(resource)
    }

    static createResource (args: PatPreferenceTypeProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-preferenceType",
            valueCoding: args.valueCoding,
        } as unknown as Extension
        return resource
    }

    static create (args: PatPreferenceTypeProfileParams) : PatPreferenceTypeProfile {
        return PatPreferenceTypeProfile.from(PatPreferenceTypeProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueCoding () : Coding | undefined {
        return this.resource.valueCoding as Coding | undefined
    }

    setValueCoding (value: Coding) : this {
        Object.assign(this.resource, { valueCoding: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "PatPreferenceType"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/patient-preferenceType", "PatPreferenceType"); if (e) errors.push(e) }
        if (!(r["valueCoding"] !== undefined)) {
            errors.push("value: at least one of valueCoding is required")
        }
        return errors
    }

}

