// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ResourceInstanceDescriptionProfileParams = {
    valueMarkdown: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/resource-instance-description (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class ResourceInstanceDescriptionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/resource-instance-description"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ResourceInstanceDescriptionProfile {
        return new ResourceInstanceDescriptionProfile(resource)
    }

    static createResource (args: ResourceInstanceDescriptionProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/resource-instance-description",
            valueMarkdown: args.valueMarkdown,
        } as unknown as Extension
        return resource
    }

    static create (args: ResourceInstanceDescriptionProfileParams) : ResourceInstanceDescriptionProfile {
        return ResourceInstanceDescriptionProfile.from(ResourceInstanceDescriptionProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueMarkdown () : string | undefined {
        return this.resource.valueMarkdown as string | undefined
    }

    setValueMarkdown (value: string) : this {
        Object.assign(this.resource, { valueMarkdown: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ResourceInstanceDescription"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/resource-instance-description", "ResourceInstanceDescription"); if (e) errors.push(e) }
        if (!(r["valueMarkdown"] !== undefined)) {
            errors.push("value: at least one of valueMarkdown is required")
        }
        return errors
    }

}

