// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r5-core/CodeableConcept";
import type { CodeableReference } from "../../hl7-fhir-r5-core/CodeableReference";
import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { Period } from "../../hl7-fhir-r5-core/Period";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type PatSexParameterForClinicalUseProfileParams = {
    extension: Extension[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/patient-sexParameterForClinicalUse (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class PatSexParameterForClinicalUseProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/patient-sexParameterForClinicalUse"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : PatSexParameterForClinicalUseProfile {
        return new PatSexParameterForClinicalUseProfile(resource)
    }

    static createResource (args: PatSexParameterForClinicalUseProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/patient-sexParameterForClinicalUse",
            extension: args.extension,
        } as unknown as Extension
        return resource
    }

    static create (args: PatSexParameterForClinicalUseProfileParams) : PatSexParameterForClinicalUseProfile {
        return PatSexParameterForClinicalUseProfile.from(PatSexParameterForClinicalUseProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setValue (value: CodeableConcept): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "value", valueCodeableConcept: value } as Extension)
        return this
    }

    public setPeriod (value: Period): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "period", valuePeriod: value } as Extension)
        return this
    }

    public setComment (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "comment", valueString: value } as Extension)
        return this
    }

    public setSupportingInfo (value: CodeableReference): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "supportingInfo", valueCodeableReference: value } as Extension)
        return this
    }

    public getValue (): CodeableConcept | undefined {
        const ext = this.resource.extension?.find(e => e.url === "value")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableConcept as CodeableConcept | undefined
    }

    public getValueExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "value")
        return ext
    }

    public getPeriod (): Period | undefined {
        const ext = this.resource.extension?.find(e => e.url === "period")
        return (ext as Record<string, unknown> | undefined)?.valuePeriod as Period | undefined
    }

    public getPeriodExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "period")
        return ext
    }

    public getComment (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "comment")
        return (ext as Record<string, unknown> | undefined)?.valueString as string | undefined
    }

    public getCommentExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "comment")
        return ext
    }

    public getSupportingInfo (): CodeableReference | undefined {
        const ext = this.resource.extension?.find(e => e.url === "supportingInfo")
        return (ext as Record<string, unknown> | undefined)?.valueCodeableReference as CodeableReference | undefined
    }

    public getSupportingInfoExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "supportingInfo")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "PatSexParameterForClinicalUse"); if (e) errors.push(e) }
        { const e = validateRequired(r, "url", "PatSexParameterForClinicalUse"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/patient-sexParameterForClinicalUse", "PatSexParameterForClinicalUse"); if (e) errors.push(e) }
        return errors
    }

}

