// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-publicationDate (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class PublicationDateProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-publicationDate"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : PublicationDateProfile {
        return new PublicationDateProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-publicationDate",
        } as unknown as Extension
        return resource
    }

    static create () : PublicationDateProfile {
        return PublicationDateProfile.from(PublicationDateProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueDate () : string | undefined {
        return this.resource.valueDate as string | undefined
    }

    setValueDate (value: string) : this {
        Object.assign(this.resource, { valueDate: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "PublicationDate"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/cqf-publicationDate", "PublicationDate"); if (e) errors.push(e) }
        return errors
    }

}

