// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ConsentNotificationEndpointProfileParams = {
    valueUri: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/consent-NotificationEndpoint (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class ConsentNotificationEndpointProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/consent-NotificationEndpoint"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ConsentNotificationEndpointProfile {
        return new ConsentNotificationEndpointProfile(resource)
    }

    static createResource (args: ConsentNotificationEndpointProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/consent-NotificationEndpoint",
            valueUri: args.valueUri,
        } as unknown as Extension
        return resource
    }

    static create (args: ConsentNotificationEndpointProfileParams) : ConsentNotificationEndpointProfile {
        return ConsentNotificationEndpointProfile.from(ConsentNotificationEndpointProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueUri () : string | undefined {
        return this.resource.valueUri as string | undefined
    }

    setValueUri (value: string) : this {
        Object.assign(this.resource, { valueUri: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ConsentNotificationEndpoint"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/consent-NotificationEndpoint", "ConsentNotificationEndpoint"); if (e) errors.push(e) }
        if (!(r["valueUri"] !== undefined)) {
            errors.push("value: at least one of valueUri is required")
        }
        return errors
    }

}

