// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ItemWeightProfileParams = {
    valueDecimal: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/itemWeight (pkg: hl7.fhir.uv.extensions#5.1.0-snapshot1)
export class ItemWeightProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/itemWeight"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ItemWeightProfile {
        return new ItemWeightProfile(resource)
    }

    static createResource (args: ItemWeightProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/itemWeight",
            valueDecimal: args.valueDecimal,
        } as unknown as Extension
        return resource
    }

    static create (args: ItemWeightProfileParams) : ItemWeightProfile {
        return ItemWeightProfile.from(ItemWeightProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueDecimal () : number | undefined {
        return this.resource.valueDecimal as number | undefined
    }

    setValueDecimal (value: number) : this {
        Object.assign(this.resource, { valueDecimal: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ItemWeight"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/itemWeight", "ItemWeight"); if (e) errors.push(e) }
        if (!(r["valueDecimal"] !== undefined)) {
            errors.push("value: at least one of valueDecimal is required")
        }
        return errors
    }

}

