// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ADXP_additionalLocatorProfileParams = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-additionalLocator (pkg: hl7.fhir.r4.core#4.0.1)
export class ADXP_additionalLocatorProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-additionalLocator"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ADXP_additionalLocatorProfile {
        return new ADXP_additionalLocatorProfile(resource)
    }

    static createResource (args: ADXP_additionalLocatorProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-additionalLocator",
            valueString: args.valueString,
        } as unknown as Extension
        return resource
    }

    static create (args: ADXP_additionalLocatorProfileParams) : ADXP_additionalLocatorProfile {
        return ADXP_additionalLocatorProfile.from(ADXP_additionalLocatorProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ADXP-additionalLocator"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-additionalLocator", "ADXP-additionalLocator"); if (e) errors.push(e) }
        if (!(r["valueString"] !== undefined)) {
            errors.push("value: at least one of valueString is required")
        }
        return errors
    }

}

