// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type Human_LanguageProfileParams = {
    valueCode: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/language (pkg: hl7.fhir.r4.core#4.0.1)
export class Human_LanguageProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/language"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : Human_LanguageProfile {
        return new Human_LanguageProfile(resource)
    }

    static createResource (args: Human_LanguageProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/language",
            valueCode: args.valueCode,
        } as unknown as Extension
        return resource
    }

    static create (args: Human_LanguageProfileParams) : Human_LanguageProfile {
        return Human_LanguageProfile.from(Human_LanguageProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueCode () : string | undefined {
        return this.resource.valueCode as string | undefined
    }

    setValueCode (value: string) : this {
        Object.assign(this.resource, { valueCode: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "Human Language"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/language", "Human Language"); if (e) errors.push(e) }
        if (!(r["valueCode"] !== undefined)) {
            errors.push("value: at least one of valueCode is required")
        }
        return errors
    }

}

