// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type Rendered_ValueProfileParams = {
    valueString: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/rendered-value (pkg: hl7.fhir.r4.core#4.0.1)
export class Rendered_ValueProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/rendered-value"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : Rendered_ValueProfile {
        return new Rendered_ValueProfile(resource)
    }

    static createResource (args: Rendered_ValueProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/rendered-value",
            valueString: args.valueString,
        } as unknown as Extension
        return resource
    }

    static create (args: Rendered_ValueProfileParams) : Rendered_ValueProfile {
        return Rendered_ValueProfile.from(Rendered_ValueProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "Rendered Value"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/rendered-value", "Rendered Value"); if (e) errors.push(e) }
        if (!(r["valueString"] !== undefined)) {
            errors.push("value: at least one of valueString is required")
        }
        return errors
    }

}

