// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type namespaceProfileParams = {
    valueUri: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/elementdefinition-namespace (pkg: hl7.fhir.r4.core#4.0.1)
export class namespaceProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/elementdefinition-namespace"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : namespaceProfile {
        return new namespaceProfile(resource)
    }

    static createResource (args: namespaceProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/elementdefinition-namespace",
            valueUri: args.valueUri,
        } as unknown as Extension
        return resource
    }

    static create (args: namespaceProfileParams) : namespaceProfile {
        return namespaceProfile.from(namespaceProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueUri () : string | undefined {
        return this.resource.valueUri as string | undefined
    }

    setValueUri (value: string) : this {
        Object.assign(this.resource, { valueUri: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "namespace"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/elementdefinition-namespace", "namespace"); if (e) errors.push(e) }
        if (!(r["valueUri"] !== undefined)) {
            errors.push("value: at least one of valueUri is required")
        }
        return errors
    }

}

