// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type receivingOrganizationProfileParams = {
    valueReference: Reference;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cqf-receivingOrganization (pkg: hl7.fhir.r4.core#4.0.1)
export class receivingOrganizationProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/cqf-receivingOrganization"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : receivingOrganizationProfile {
        return new receivingOrganizationProfile(resource)
    }

    static createResource (args: receivingOrganizationProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/cqf-receivingOrganization",
            valueReference: args.valueReference,
        } as unknown as Extension
        return resource
    }

    static create (args: receivingOrganizationProfileParams) : receivingOrganizationProfile {
        return receivingOrganizationProfile.from(receivingOrganizationProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueReference () : Reference | undefined {
        return this.resource.valueReference as Reference | undefined
    }

    setValueReference (value: Reference) : this {
        Object.assign(this.resource, { valueReference: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "receivingOrganization"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/cqf-receivingOrganization", "receivingOrganization"); if (e) errors.push(e) }
        if (!(r["valueReference"] !== undefined)) {
            errors.push("value: at least one of valueReference is required")
        }
        return errors
    }

}

