// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/procedure-directedBy (pkg: hl7.fhir.r4.core#4.0.1)
export class directedByProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/procedure-directedBy"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : directedByProfile {
        return new directedByProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/procedure-directedBy",
        } as unknown as Extension
        return resource
    }

    static create () : directedByProfile {
        return directedByProfile.from(directedByProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value })
        return this
    }

    getValueReference () : Reference | undefined {
        return this.resource.valueReference as Reference | undefined
    }

    setValueReference (value: Reference) : this {
        Object.assign(this.resource, { valueReference: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "directedBy"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/procedure-directedBy", "directedBy"); if (e) errors.push(e) }
        if (!(r["valueCodeableConcept"] !== undefined || r["valueReference"] !== undefined)) {
            errors.push("value: at least one of valueCodeableConcept, valueReference is required")
        }
        return errors
    }

}

