// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r4-core/Observation";
import type { Period } from "../../hl7-fhir-r4-core/Period";
import type { Quantity } from "../../hl7-fhir-r4-core/Quantity";
import type { Range } from "../../hl7-fhir-r4-core/Range";
import type { Ratio } from "../../hl7-fhir-r4-core/Ratio";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";
import type { SampledData } from "../../hl7-fhir-r4-core/SampledData";

export interface Device_Metric_Observation_Profile extends Observation {
    subject: Reference<"Device" | "Patient">;
    effectiveDateTime: string;
    device: Reference<"DeviceMetric">;
    hasMember?: Reference<"Observation">[];
    derivedFrom?: Reference<"Observation">[];
}

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type Device_Metric_Observation_ProfileProfileParams = {
    status: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown");
    code: CodeableConcept;
    subject: Reference<"Device" | "Patient">;
    device: Reference<"DeviceMetric">;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/devicemetricobservation (pkg: hl7.fhir.r4.core#4.0.1)
export class Device_Metric_Observation_ProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/devicemetricobservation"

    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/devicemetricobservation")) profiles.push("http://hl7.org/fhir/StructureDefinition/devicemetricobservation")
    }

    static from (resource: Observation) : Device_Metric_Observation_ProfileProfile {
        return new Device_Metric_Observation_ProfileProfile(resource)
    }

    static createResource (args: Device_Metric_Observation_ProfileProfileParams) : Observation {
        const resource: Observation = {
            resourceType: "Observation",
            status: args.status,
            code: args.code,
            subject: args.subject,
            device: args.device,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/devicemetricobservation"] },
        } as unknown as Observation
        return resource
    }

    static create (args: Device_Metric_Observation_ProfileProfileParams) : Device_Metric_Observation_ProfileProfile {
        return Device_Metric_Observation_ProfileProfile.from(Device_Metric_Observation_ProfileProfile.createResource(args))
    }

    toResource () : Observation {
        return this.resource
    }

    getStatus () : ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined {
        return this.resource.status as ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown") | undefined
    }

    setStatus (value: ("registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error" | "unknown")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getCode () : CodeableConcept | undefined {
        return this.resource.code as CodeableConcept | undefined
    }

    setCode (value: CodeableConcept) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getSubject () : Reference<"Device" | "Patient"> | undefined {
        return this.resource.subject as Reference<"Device" | "Patient"> | undefined
    }

    setSubject (value: Reference<"Device" | "Patient">) : this {
        Object.assign(this.resource, { subject: value })
        return this
    }

    getDevice () : Reference<"DeviceMetric"> | undefined {
        return this.resource.device as Reference<"DeviceMetric"> | undefined
    }

    setDevice (value: Reference<"DeviceMetric">) : this {
        Object.assign(this.resource, { device: value })
        return this
    }

    getEffectiveDateTime () : string | undefined {
        return this.resource.effectiveDateTime as string | undefined
    }

    setEffectiveDateTime (value: string) : this {
        Object.assign(this.resource, { effectiveDateTime: value })
        return this
    }

    getValueQuantity () : Quantity | undefined {
        return this.resource.valueQuantity as Quantity | undefined
    }

    setValueQuantity (value: Quantity) : this {
        Object.assign(this.resource, { valueQuantity: value })
        return this
    }

    getValueCodeableConcept () : CodeableConcept | undefined {
        return this.resource.valueCodeableConcept as CodeableConcept | undefined
    }

    setValueCodeableConcept (value: CodeableConcept) : this {
        Object.assign(this.resource, { valueCodeableConcept: value })
        return this
    }

    getValueString () : string | undefined {
        return this.resource.valueString as string | undefined
    }

    setValueString (value: string) : this {
        Object.assign(this.resource, { valueString: value })
        return this
    }

    getValueRange () : Range | undefined {
        return this.resource.valueRange as Range | undefined
    }

    setValueRange (value: Range) : this {
        Object.assign(this.resource, { valueRange: value })
        return this
    }

    getValueRatio () : Ratio | undefined {
        return this.resource.valueRatio as Ratio | undefined
    }

    setValueRatio (value: Ratio) : this {
        Object.assign(this.resource, { valueRatio: value })
        return this
    }

    getValueSampledData () : SampledData | undefined {
        return this.resource.valueSampledData as SampledData | undefined
    }

    setValueSampledData (value: SampledData) : this {
        Object.assign(this.resource, { valueSampledData: value })
        return this
    }

    getValueTime () : string | undefined {
        return this.resource.valueTime as string | undefined
    }

    setValueTime (value: string) : this {
        Object.assign(this.resource, { valueTime: value })
        return this
    }

    getValueDateTime () : string | undefined {
        return this.resource.valueDateTime as string | undefined
    }

    setValueDateTime (value: string) : this {
        Object.assign(this.resource, { valueDateTime: value })
        return this
    }

    getValuePeriod () : Period | undefined {
        return this.resource.valuePeriod as Period | undefined
    }

    setValuePeriod (value: Period) : this {
        Object.assign(this.resource, { valuePeriod: value })
        return this
    }

    toProfile () : Device_Metric_Observation_Profile {
        return this.resource as Device_Metric_Observation_Profile
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "status", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["registered","preliminary","final","amended","corrected","cancelled","entered-in-error","unknown"], "status", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "code", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "subject", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["subject"], ["Device","Patient"], "subject", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["encounter"], ["Encounter"], "encounter", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["specimen"], ["Specimen"], "specimen", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "device", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["device"], ["DeviceMetric"], "device", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["hasMember"], ["Observation"], "hasMember", "Device Metric Observation Profile"); if (e) errors.push(e) }
        { const e = validateReference(r["derivedFrom"], ["Observation"], "derivedFrom", "Device Metric Observation Profile"); if (e) errors.push(e) }
        return errors
    }

}

