// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r4-core/CodeableConcept";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { Reference } from "../../hl7-fhir-r4-core/Reference";
import type { ServiceRequest } from "../../hl7-fhir-r4-core/ServiceRequest";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/servicerequest-genetics
export type ServiceRequest_Genetics_ItemInput = {
    code: CodeableConcept;
    geneticsObservation?: Reference;
    specimen?: Reference;
    status?: code;
}

export class ServiceRequest_GeneticsProfile {
    private resource: ServiceRequest

    constructor (resource?: ServiceRequest) {
        this.resource = resource ?? ({ resourceType: "ServiceRequest" } as ServiceRequest)
    }

    toResource () : ServiceRequest {
        return this.resource
    }

    public setItem (input: ServiceRequest_Genetics_ItemInput): this {
        const subExtensions: Extension[] = []
        if (input.code !== undefined) {
            subExtensions.push({ url: "code", valueCodeableConcept: input.code })
        }
        if (input.geneticsObservation !== undefined) {
            subExtensions.push({ url: "geneticsObservation", valueReference: input.geneticsObservation })
        }
        if (input.specimen !== undefined) {
            subExtensions.push({ url: "specimen", valueReference: input.specimen })
        }
        if (input.status !== undefined) {
            subExtensions.push({ url: "status", valueCode: input.status })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/servicerequest-geneticsItem", extension: subExtensions })
        return this
    }

    public resetItem (): this {
        const list = this.resource.extension
        if (list) {
            const index = list.findIndex((e) => e.url === "http://hl7.org/fhir/StructureDefinition/servicerequest-geneticsItem")
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

}

