// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/orgs/atomic-ehr/repositories
// Any manual changes made to this file may be overwritten.

import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { Element } from "../hl7-fhir-r4-core/Element";

export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Element } from "../hl7-fhir-r4-core/Element";

export interface Contributor extends Element {
    contact?: ContactDetail[];
    name: string;
    _name?: Element;
    type_: "author" | "editor" | "reviewer" | "endorser";
    _type_?: Element;
}
