// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type OOIssueLineProfileParams = {
    valueInteger: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line (pkg: hl7.fhir.uv.extensions.r4#5.2.0)
export class OOIssueLineProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : OOIssueLineProfile {
        return new OOIssueLineProfile(resource)
    }

    static createResource (args: OOIssueLineProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line",
            valueInteger: args.valueInteger,
        } as unknown as Extension
        return resource
    }

    static create (args: OOIssueLineProfileParams) : OOIssueLineProfile {
        return OOIssueLineProfile.from(OOIssueLineProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueInteger () : number | undefined {
        return this.resource.valueInteger as number | undefined
    }

    setValueInteger (value: number) : this {
        Object.assign(this.resource, { valueInteger: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "OOIssueLine"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/operationoutcome-issue-line", "OOIssueLine"); if (e) errors.push(e) }
        if (!(r["valueInteger"] !== undefined)) {
            errors.push("value: at least one of valueInteger is required")
        }
        return errors
    }

}

