// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { ContactDetail } from "../../hl7-fhir-r4-core/ContactDetail";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ArtifactReviewerProfileParams = {
    valueContactDetail: ContactDetail;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/artifact-reviewer (pkg: hl7.fhir.uv.extensions.r4#5.2.0)
export class ArtifactReviewerProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/artifact-reviewer"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ArtifactReviewerProfile {
        return new ArtifactReviewerProfile(resource)
    }

    static createResource (args: ArtifactReviewerProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/artifact-reviewer",
            valueContactDetail: args.valueContactDetail,
        } as unknown as Extension
        return resource
    }

    static create (args: ArtifactReviewerProfileParams) : ArtifactReviewerProfile {
        return ArtifactReviewerProfile.from(ArtifactReviewerProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueContactDetail () : ContactDetail | undefined {
        return this.resource.valueContactDetail as ContactDetail | undefined
    }

    setValueContactDetail (value: ContactDetail) : this {
        Object.assign(this.resource, { valueContactDetail: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ArtifactReviewer"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/artifact-reviewer", "ArtifactReviewer"); if (e) errors.push(e) }
        if (!(r["valueContactDetail"] !== undefined)) {
            errors.push("value: at least one of valueContactDetail is required")
        }
        return errors
    }

}

