// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r4-core/Extension";
import type { UsageContext } from "../../hl7-fhir-r4-core/UsageContext";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ArtifactUseContextProfileParams = {
    valueUsageContext: UsageContext;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/artifact-useContext (pkg: hl7.fhir.uv.extensions.r4#5.2.0)
export class ArtifactUseContextProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/artifact-useContext"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : ArtifactUseContextProfile {
        return new ArtifactUseContextProfile(resource)
    }

    static createResource (args: ArtifactUseContextProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/artifact-useContext",
            valueUsageContext: args.valueUsageContext,
        } as unknown as Extension
        return resource
    }

    static create (args: ArtifactUseContextProfileParams) : ArtifactUseContextProfile {
        return ArtifactUseContextProfile.from(ArtifactUseContextProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getValueUsageContext () : UsageContext | undefined {
        return this.resource.valueUsageContext as UsageContext | undefined
    }

    setValueUsageContext (value: UsageContext) : this {
        Object.assign(this.resource, { valueUsageContext: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ArtifactUseContext"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/artifact-useContext", "ArtifactUseContext"); if (e) errors.push(e) }
        if (!(r["valueUsageContext"] !== undefined)) {
            errors.push("value: at least one of valueUsageContext is required")
        }
        return errors
    }

}

