// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Expression } from "../../hl7-fhir-r4-core/Expression";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type QOptionRestrictionProfileParams = {
    extension: Extension[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/questionnaire-optionRestriction (pkg: hl7.fhir.uv.extensions.r4#5.2.0)
export class QOptionRestrictionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/questionnaire-optionRestriction"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : QOptionRestrictionProfile {
        return new QOptionRestrictionProfile(resource)
    }

    static createResource (args: QOptionRestrictionProfileParams) : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/questionnaire-optionRestriction",
            extension: args.extension,
        } as unknown as Extension
        return resource
    }

    static create (args: QOptionRestrictionProfileParams) : QOptionRestrictionProfile {
        return QOptionRestrictionProfile.from(QOptionRestrictionProfile.createResource(args))
    }

    toResource () : Extension {
        return this.resource
    }

    getExtension () : Extension[] | undefined {
        return this.resource.extension as Extension[] | undefined
    }

    setExtension (value: Extension[]) : this {
        Object.assign(this.resource, { extension: value })
        return this
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setOption (value: number): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "option", valueInteger: value } as Extension)
        return this
    }

    public setExpression (value: Expression): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "requirements", valueExpression: value } as Extension)
        return this
    }

    public getOption (): number | undefined {
        const ext = this.resource.extension?.find(e => e.url === "option")
        return (ext as Record<string, unknown> | undefined)?.valueInteger as number | undefined
    }

    public getOptionExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "option")
        return ext
    }

    public getExpression (): Expression | undefined {
        const ext = this.resource.extension?.find(e => e.url === "requirements")
        return (ext as Record<string, unknown> | undefined)?.valueExpression as Expression | undefined
    }

    public getExpressionExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "requirements")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "extension", "QOptionRestriction"); if (e) errors.push(e) }
        { const e = validateRequired(r, "url", "QOptionRestriction"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/questionnaire-optionRestriction", "QOptionRestriction"); if (e) errors.push(e) }
        return errors
    }

}

