// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Coding } from "../../hl7-fhir-r4-core/Coding";
import type { Extension } from "../../hl7-fhir-r4-core/Extension";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/organization-brand (pkg: hl7.fhir.uv.extensions.r4#5.2.0)
export class OrganizationBrandProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/organization-brand"

    private resource: Extension

    constructor (resource: Extension) {
        this.resource = resource
    }

    static from (resource: Extension) : OrganizationBrandProfile {
        return new OrganizationBrandProfile(resource)
    }

    static createResource () : Extension {
        const resource: Extension = {
            url: "http://hl7.org/fhir/StructureDefinition/organization-brand",
        } as unknown as Extension
        return resource
    }

    static create () : OrganizationBrandProfile {
        return OrganizationBrandProfile.from(OrganizationBrandProfile.createResource())
    }

    toResource () : Extension {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    public setBrandLogo (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "brandLogo", valueUrl: value } as Extension)
        return this
    }

    public setBrandLogoLicenseType (value: Coding): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "brandLogoLicenseType", valueCoding: value } as Extension)
        return this
    }

    public setBrandLogoLicense (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "brandLogoLicense", valueUrl: value } as Extension)
        return this
    }

    public setBrandBundle (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "brandBundle", valueUrl: value } as Extension)
        return this
    }

    public getBrandLogo (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogo")
        return (ext as Record<string, unknown> | undefined)?.valueUrl as string | undefined
    }

    public getBrandLogoExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogo")
        return ext
    }

    public getBrandLogoLicenseType (): Coding | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogoLicenseType")
        return (ext as Record<string, unknown> | undefined)?.valueCoding as Coding | undefined
    }

    public getBrandLogoLicenseTypeExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogoLicenseType")
        return ext
    }

    public getBrandLogoLicense (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogoLicense")
        return (ext as Record<string, unknown> | undefined)?.valueUrl as string | undefined
    }

    public getBrandLogoLicenseExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandLogoLicense")
        return ext
    }

    public getBrandBundle (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandBundle")
        return (ext as Record<string, unknown> | undefined)?.valueUrl as string | undefined
    }

    public getBrandBundleExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "brandBundle")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "OrganizationBrand"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "url", "http://hl7.org/fhir/StructureDefinition/organization-brand", "OrganizationBrand"); if (e) errors.push(e) }
        return errors
    }

}

