// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { RequestOrchestration } from "../../hl7-fhir-r5-core/RequestOrchestration";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/cdshooksrequestorchestration
export class CDSHooksRequestOrchestrationProfile {
    private resource: RequestOrchestration

    constructor (resource?: RequestOrchestration) {
        this.resource = resource ?? ({ resourceType: "RequestOrchestration" } as RequestOrchestration)
    }

    toResource () : RequestOrchestration {
        return this.resource
    }

}

