// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r5-core/CodeableConcept";
import type { DiagnosticReport } from "../../hl7-fhir-r5-core/DiagnosticReport";

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/lipidprofile (pkg: hl7.fhir.r5.core#5.0.0)
export class ExampleLipidProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/lipidprofile"

    private resource: DiagnosticReport

    constructor (resource: DiagnosticReport) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/lipidprofile")) profiles.push("http://hl7.org/fhir/StructureDefinition/lipidprofile")
    }

    static from (resource: DiagnosticReport) : ExampleLipidProfileProfile {
        return new ExampleLipidProfileProfile(resource)
    }

    static createResource () : DiagnosticReport {
        const resource: DiagnosticReport = {
            resourceType: "DiagnosticReport",
            code: {"coding":[{"system":"http://loinc.org","code":"57698-3","display":"Lipid panel with direct LDL - Serum or Plasma"}]},
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/lipidprofile"] },
        } as unknown as DiagnosticReport
        return resource
    }

    static create () : ExampleLipidProfileProfile {
        return ExampleLipidProfileProfile.from(ExampleLipidProfileProfile.createResource())
    }

    toResource () : DiagnosticReport {
        return this.resource
    }

    getCode () : CodeableConcept | undefined {
        return this.resource.code as CodeableConcept | undefined
    }

    setCode (value: CodeableConcept) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "code", "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateFixedValue(r, "code", {"coding":[{"system":"http://loinc.org","code":"57698-3","display":"Lipid panel with direct LDL - Serum or Plasma"}]}, "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["result"], ["Observation"], "result", "ExampleLipidProfile"); if (e) errors.push(e) }
        return errors
    }

}

