// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Composition } from "../../hl7-fhir-r5-core/Composition";
import type { CompositionSection } from "../../hl7-fhir-r5-core/Composition";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/example-section-library
export type DocumentSectionLibrary_Section_ProcedureSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;
export type DocumentSectionLibrary_Section_MedicationsSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;
export type DocumentSectionLibrary_Section_PlanSliceInput = Omit<CompositionSection, "code"> & Required<Pick<CompositionSection, "title">>;

import { applySliceMatch, matchesSlice, extractSliceSimplified } from "../../profile-helpers";

export class DocumentSectionLibraryProfile {
    private resource: Composition

    constructor (resource: Composition) {
        this.resource = resource
    }

    toResource () : Composition {
        return this.resource
    }

    public setProcedure (input: DocumentSectionLibrary_Section_ProcedureSliceInput): this {
        const match = {"code":{"coding":[{"code":"29554-3","display":"Procedure Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setMedications (input: DocumentSectionLibrary_Section_MedicationsSliceInput): this {
        const match = {"code":{"coding":[{"code":"29549-3","display":"Medication administered Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public setPlan (input: DocumentSectionLibrary_Section_PlanSliceInput): this {
        const match = {"code":{"coding":[{"code":"18776-5","display":"Plan of treatment (narrative)","system":"http://loinc.org"}]}} as Record<string, unknown>
        const value = applySliceMatch(input as Record<string, unknown>, match) as unknown as CompositionSection
        const list = (this.resource.section ??= [])
        const index = list.findIndex((item) => matchesSlice(item, match))
        if (index === -1) {
            list.push(value)
        } else {
            list[index] = value
        }
        return this
    }

    public resetProcedure (): this {
        const match = {"code":{"coding":[{"code":"29554-3","display":"Procedure Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (list) {
            const index = list.findIndex((item) => matchesSlice(item, match))
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetMedications (): this {
        const match = {"code":{"coding":[{"code":"29549-3","display":"Medication administered Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (list) {
            const index = list.findIndex((item) => matchesSlice(item, match))
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public resetPlan (): this {
        const match = {"code":{"coding":[{"code":"18776-5","display":"Plan of treatment (narrative)","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (list) {
            const index = list.findIndex((item) => matchesSlice(item, match))
            if (index !== -1) {
                list.splice(index, 1)
            }
        }
        return this
    }

    public getProcedure(raw: true): CompositionSection | undefined
    public getProcedure(raw?: false): DocumentSectionLibrary_Section_ProcedureSliceInput | undefined
    public getProcedure (raw?: boolean): CompositionSection | DocumentSectionLibrary_Section_ProcedureSliceInput | undefined {
        const match = {"code":{"coding":[{"code":"29554-3","display":"Procedure Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        if (raw) return item
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_ProcedureSliceInput
    }

    public getMedications(raw: true): CompositionSection | undefined
    public getMedications(raw?: false): DocumentSectionLibrary_Section_MedicationsSliceInput | undefined
    public getMedications (raw?: boolean): CompositionSection | DocumentSectionLibrary_Section_MedicationsSliceInput | undefined {
        const match = {"code":{"coding":[{"code":"29549-3","display":"Medication administered Narrative","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        if (raw) return item
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_MedicationsSliceInput
    }

    public getPlan(raw: true): CompositionSection | undefined
    public getPlan(raw?: false): DocumentSectionLibrary_Section_PlanSliceInput | undefined
    public getPlan (raw?: boolean): CompositionSection | DocumentSectionLibrary_Section_PlanSliceInput | undefined {
        const match = {"code":{"coding":[{"code":"18776-5","display":"Plan of treatment (narrative)","system":"http://loinc.org"}]}} as Record<string, unknown>
        const list = this.resource.section
        if (!list) return undefined
        const item = list.find((item) => matchesSlice(item, match))
        if (!item) return undefined
        if (raw) return item
        return extractSliceSimplified(item as unknown as Record<string, unknown>, ["code"]) as DocumentSectionLibrary_Section_PlanSliceInput
    }

}

