// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../../hl7-fhir-r5-core/CodeableConcept";
import type { Observation } from "../../hl7-fhir-r5-core/Observation";
import type { ObservationReferenceRange } from "../../hl7-fhir-r5-core/Observation";
import type { Quantity } from "../../hl7-fhir-r5-core/Quantity";

export interface ExampleLipidProfile extends Observation {
    referenceRange: ObservationReferenceRange[];
}

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ExampleLipidProfileProfileParams = {
    code: CodeableConcept<("18262-6" | "13457-7")>;
    referenceRange: ObservationReferenceRange[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ldlcholesterol (pkg: hl7.fhir.r5.core#5.0.0)
export class ExampleLipidProfileProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/ldlcholesterol"

    private resource: Observation

    constructor (resource: Observation) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/ldlcholesterol")) profiles.push("http://hl7.org/fhir/StructureDefinition/ldlcholesterol")
    }

    static from (resource: Observation) : ExampleLipidProfileProfile {
        return new ExampleLipidProfileProfile(resource)
    }

    static createResource (args: ExampleLipidProfileProfileParams) : Observation {
        const resource: Observation = {
            resourceType: "Observation",
            code: args.code,
            referenceRange: args.referenceRange,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/ldlcholesterol"] },
        } as unknown as Observation
        return resource
    }

    static create (args: ExampleLipidProfileProfileParams) : ExampleLipidProfileProfile {
        return ExampleLipidProfileProfile.from(ExampleLipidProfileProfile.createResource(args))
    }

    toResource () : Observation {
        return this.resource
    }

    getCode () : CodeableConcept<("18262-6" | "13457-7")> | undefined {
        return this.resource.code as CodeableConcept<("18262-6" | "13457-7")> | undefined
    }

    setCode (value: CodeableConcept<("18262-6" | "13457-7")>) : this {
        Object.assign(this.resource, { code: value })
        return this
    }

    getReferenceRange () : ObservationReferenceRange[] | undefined {
        return this.resource.referenceRange as ObservationReferenceRange[] | undefined
    }

    setReferenceRange (value: ObservationReferenceRange[]) : this {
        Object.assign(this.resource, { referenceRange: value })
        return this
    }

    getValueQuantity () : Quantity | undefined {
        return this.resource.valueQuantity as Quantity | undefined
    }

    setValueQuantity (value: Quantity) : this {
        Object.assign(this.resource, { valueQuantity: value })
        return this
    }

    toProfile () : ExampleLipidProfile {
        return this.resource as ExampleLipidProfile
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "code", "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateEnum(r["code"], ["18262-6","13457-7"], "code", "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateRequired(r, "referenceRange", "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["hasMember"], ["MolecularSequence","Observation","QuestionnaireResponse"], "hasMember", "ExampleLipidProfile"); if (e) errors.push(e) }
        { const e = validateReference(r["derivedFrom"], ["DocumentReference","GenomicStudy","ImagingSelection","ImagingStudy","MolecularSequence","Observation","QuestionnaireResponse"], "derivedFrom", "ExampleLipidProfile"); if (e) errors.push(e) }
        return errors
    }

}

