// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { PlanDefinition } from "../../hl7-fhir-r5-core/PlanDefinition";

export interface PublishablePlanDefinition extends PlanDefinition {
    url: string;
    version: string;
    title: string;
    description: string;
    date: string;
}

export type PublishablePlanDefinition_ArtifactCommentInput = {
    type: string;
    text: string;
    target?: string[];
    reference?: string[];
    user?: string;
    authoredOn?: string;
}

import { extractComplexExtension, validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type PublishablePlanDefinitionProfileParams = {
    url: string;
    version: string;
    title: string;
    description: string;
    date: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/publishableplandefinition (pkg: hl7.fhir.r5.core#5.0.0)
export class PublishablePlanDefinitionProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/publishableplandefinition"

    private resource: PlanDefinition

    constructor (resource: PlanDefinition) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/publishableplandefinition")) profiles.push("http://hl7.org/fhir/StructureDefinition/publishableplandefinition")
    }

    static from (resource: PlanDefinition) : PublishablePlanDefinitionProfile {
        return new PublishablePlanDefinitionProfile(resource)
    }

    static createResource (args: PublishablePlanDefinitionProfileParams) : PlanDefinition {
        const resource: PlanDefinition = {
            resourceType: "PlanDefinition",
            url: args.url,
            version: args.version,
            title: args.title,
            description: args.description,
            date: args.date,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/publishableplandefinition"] },
        } as unknown as PlanDefinition
        return resource
    }

    static create (args: PublishablePlanDefinitionProfileParams) : PublishablePlanDefinitionProfile {
        return PublishablePlanDefinitionProfile.from(PublishablePlanDefinitionProfile.createResource(args))
    }

    toResource () : PlanDefinition {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getVersion () : string | undefined {
        return this.resource.version as string | undefined
    }

    setVersion (value: string) : this {
        Object.assign(this.resource, { version: value })
        return this
    }

    getTitle () : string | undefined {
        return this.resource.title as string | undefined
    }

    setTitle (value: string) : this {
        Object.assign(this.resource, { title: value })
        return this
    }

    getDescription () : string | undefined {
        return this.resource.description as string | undefined
    }

    setDescription (value: string) : this {
        Object.assign(this.resource, { description: value })
        return this
    }

    getDate () : string | undefined {
        return this.resource.date as string | undefined
    }

    setDate (value: string) : this {
        Object.assign(this.resource, { date: value })
        return this
    }

    toProfile () : PublishablePlanDefinition {
        return this.resource as PublishablePlanDefinition
    }

    public setKnowledgeCapability (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeCapability", valueCode: value } as Extension)
        return this
    }

    public setKnowledgeRepresentationLevel (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel", valueCode: value } as Extension)
        return this
    }

    public setArtifactComment (input: PublishablePlanDefinition_ArtifactCommentInput): this {
        const subExtensions: Extension[] = []
        if (input.type !== undefined) {
            subExtensions.push({ url: "type", valueCode: input.type })
        }
        if (input.text !== undefined) {
            subExtensions.push({ url: "text", valueMarkdown: input.text })
        }
        if (input.target) {
            for (const item of input.target) {
                subExtensions.push({ url: "target", valueUri: item })
            }
        }
        if (input.reference) {
            for (const item of input.reference) {
                subExtensions.push({ url: "reference", valueUri: item })
            }
        }
        if (input.user !== undefined) {
            subExtensions.push({ url: "user", valueString: input.user })
        }
        if (input.authoredOn !== undefined) {
            subExtensions.push({ url: "authoredOn", valueDateTime: input.authoredOn })
        }
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-artifactComment", extension: subExtensions })
        return this
    }

    public getKnowledgeCapability (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeCapability")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getKnowledgeCapabilityExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeCapability")
        return ext
    }

    public getKnowledgeRepresentationLevel (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getKnowledgeRepresentationLevelExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel")
        return ext
    }

    public getArtifactComment (): PublishablePlanDefinition_ArtifactCommentInput | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-artifactComment")
        if (!ext) return undefined
        const config = [{ name: "type", valueField: "valueCode", isArray: false }, { name: "text", valueField: "valueMarkdown", isArray: false }, { name: "target", valueField: "valueUri", isArray: true }, { name: "reference", valueField: "valueUri", isArray: true }, { name: "user", valueField: "valueString", isArray: false }, { name: "authoredOn", valueField: "valueDateTime", isArray: false }]
        return extractComplexExtension(ext as unknown as { extension?: Array<{ url?: string; [key: string]: unknown }> }, config) as PublishablePlanDefinition_ArtifactCommentInput
    }

    public getArtifactCommentExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-artifactComment")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "PublishablePlanDefinition"); if (e) errors.push(e) }
        { const e = validateRequired(r, "version", "PublishablePlanDefinition"); if (e) errors.push(e) }
        { const e = validateRequired(r, "title", "PublishablePlanDefinition"); if (e) errors.push(e) }
        { const e = validateRequired(r, "description", "PublishablePlanDefinition"); if (e) errors.push(e) }
        { const e = validateRequired(r, "date", "PublishablePlanDefinition"); if (e) errors.push(e) }
        return errors
    }

}

