// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { TestScript } from "../../hl7-fhir-r5-core/TestScript";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareabletestscript
export class ShareableTestScriptProfile {
    private resource: TestScript

    constructor (resource?: TestScript) {
        this.resource = resource ?? ({ resourceType: "TestScript" } as TestScript)
    }

    toResource () : TestScript {
        return this.resource
    }

}

