// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { Library } from "../../hl7-fhir-r5-core/Library";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/shareablelibrary
export interface ShareableLibrary extends Library {
    url: string;
    version: string;
    title: string;
    description: string;
}

export class ShareableLibraryProfile {
    private resource: Library

    constructor (resource: Library) {
        this.resource = resource
    }

    toResource () : Library {
        return this.resource
    }

    toProfile () : ShareableLibrary {
        return this.resource as ShareableLibrary
    }

    public setKnowledgeCapability (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeCapability", ...value })
        return this
    }

    public setKnowledgeRepresentationLevel (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel", ...value })
        return this
    }

    public setArtifactComment (value: Omit<Extension, "url">): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-artifactComment", ...value })
        return this
    }

    public getKnowledgeCapability (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeCapability")
    }

    public getKnowledgeRepresentationLevel (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel")
    }

    public getArtifactComment (): Extension | undefined {
        return this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-artifactComment")
    }

}

