// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Extension } from "../../hl7-fhir-r5-core/Extension";
import type { ValueSet } from "../../hl7-fhir-r5-core/ValueSet";
import type { ValueSetExpansion } from "../../hl7-fhir-r5-core/ValueSet";

export interface ExecutableValueSet extends ValueSet {
    url: string;
    version: string;
    title: string;
    experimental: boolean;
    description: string;
    expansion: ValueSetExpansion;
}

import { validateRequired, validateExcluded, validateFixedValue, validateSliceCardinality, validateEnum, validateReference } from "../../profile-helpers";

export type ExecutableValueSetProfileParams = {
    url: string;
    version: string;
    title: string;
    status: ("draft" | "active" | "retired" | "unknown");
    experimental: boolean;
    description: string;
    expansion: ValueSetExpansion;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/executablevalueset (pkg: hl7.fhir.r5.core#5.0.0)
export class ExecutableValueSetProfile {
    static readonly canonicalUrl = "http://hl7.org/fhir/StructureDefinition/executablevalueset"

    private resource: ValueSet

    constructor (resource: ValueSet) {
        this.resource = resource
        const r = resource as unknown as Record<string, unknown>
        const meta = (r.meta ??= {}) as Record<string, unknown>
        const profiles = (meta.profile ??= []) as string[]
        if (!profiles.includes("http://hl7.org/fhir/StructureDefinition/executablevalueset")) profiles.push("http://hl7.org/fhir/StructureDefinition/executablevalueset")
    }

    static from (resource: ValueSet) : ExecutableValueSetProfile {
        return new ExecutableValueSetProfile(resource)
    }

    static createResource (args: ExecutableValueSetProfileParams) : ValueSet {
        const resource: ValueSet = {
            resourceType: "ValueSet",
            url: args.url,
            version: args.version,
            title: args.title,
            status: args.status,
            experimental: args.experimental,
            description: args.description,
            expansion: args.expansion,
            meta: { profile: ["http://hl7.org/fhir/StructureDefinition/executablevalueset"] },
        } as unknown as ValueSet
        return resource
    }

    static create (args: ExecutableValueSetProfileParams) : ExecutableValueSetProfile {
        return ExecutableValueSetProfile.from(ExecutableValueSetProfile.createResource(args))
    }

    toResource () : ValueSet {
        return this.resource
    }

    getUrl () : string | undefined {
        return this.resource.url as string | undefined
    }

    setUrl (value: string) : this {
        Object.assign(this.resource, { url: value })
        return this
    }

    getVersion () : string | undefined {
        return this.resource.version as string | undefined
    }

    setVersion (value: string) : this {
        Object.assign(this.resource, { version: value })
        return this
    }

    getTitle () : string | undefined {
        return this.resource.title as string | undefined
    }

    setTitle (value: string) : this {
        Object.assign(this.resource, { title: value })
        return this
    }

    getStatus () : ("draft" | "active" | "retired" | "unknown") | undefined {
        return this.resource.status as ("draft" | "active" | "retired" | "unknown") | undefined
    }

    setStatus (value: ("draft" | "active" | "retired" | "unknown")) : this {
        Object.assign(this.resource, { status: value })
        return this
    }

    getExperimental () : boolean | undefined {
        return this.resource.experimental as boolean | undefined
    }

    setExperimental (value: boolean) : this {
        Object.assign(this.resource, { experimental: value })
        return this
    }

    getDescription () : string | undefined {
        return this.resource.description as string | undefined
    }

    setDescription (value: string) : this {
        Object.assign(this.resource, { description: value })
        return this
    }

    getExpansion () : ValueSetExpansion | undefined {
        return this.resource.expansion as ValueSetExpansion | undefined
    }

    setExpansion (value: ValueSetExpansion) : this {
        Object.assign(this.resource, { expansion: value })
        return this
    }

    toProfile () : ExecutableValueSet {
        return this.resource as ExecutableValueSet
    }

    public setKnowledgeRepresentationLevel (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel", valueCode: value } as Extension)
        return this
    }

    public setAuthoritativeSource (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/valueset-authoritativeSource", valueUri: value } as Extension)
        return this
    }

    public setUsageWarning (value: string): this {
        const list = (this.resource.extension ??= [])
        list.push({ url: "http://hl7.org/fhir/StructureDefinition/valueset-warning", valueMarkdown: value } as Extension)
        return this
    }

    public getKnowledgeRepresentationLevel (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel")
        return (ext as Record<string, unknown> | undefined)?.valueCode as string | undefined
    }

    public getKnowledgeRepresentationLevelExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel")
        return ext
    }

    public getAuthoritativeSource (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/valueset-authoritativeSource")
        return (ext as Record<string, unknown> | undefined)?.valueUri as string | undefined
    }

    public getAuthoritativeSourceExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/valueset-authoritativeSource")
        return ext
    }

    public getUsageWarning (): string | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/valueset-warning")
        return (ext as Record<string, unknown> | undefined)?.valueMarkdown as string | undefined
    }

    public getUsageWarningExtension (): Extension | undefined {
        const ext = this.resource.extension?.find(e => e.url === "http://hl7.org/fhir/StructureDefinition/valueset-warning")
        return ext
    }

    validate () : string[] {
        const errors: string[] = []
        const r = this.resource as unknown as Record<string, unknown>
        { const e = validateRequired(r, "url", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "version", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "title", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "status", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateEnum(r["status"], ["draft","active","retired","unknown"], "status", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "experimental", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "description", "ExecutableValueSet"); if (e) errors.push(e) }
        { const e = validateRequired(r, "expansion", "ExecutableValueSet"); if (e) errors.push(e) }
        return errors
    }

}

